### ISSUE TITLE
Render with new Value causes 2 additional onChange events

### ISSUE THREAD

**Issue by JeremyWheelks** [securingsincity/react-ace#101]
Using initEditor method in ref causes additional SetValue call after receiving props with new value.

initEditor should be called only once in componentDidMount callback.

**Comment by JeremyWheelks** [comment]
Actually the problem is ref callback calling not only after component was mounted, but on each render

**Comment by wldcordeiro** [comment]
This issue is critical as I found that it can cause infinite loops and had to revert back to 2.6.0

**Comment by kolis** [comment]
I have the same problem with infinite looping! Downgrade to 3.3.0 works for me

**Comment by wldcordeiro** [comment]
@kolis I had to do the same. Though I think I downgraded to 2.6.0 as that was the previous version I was using.

**Comment by shawnbissell** [comment]
+1 I had to downgrade to 3.3.0 as well

**Comment by jueast08** [comment]
+1 downgrade to 3.3.0 fixed the issue for me

**Comment by securingsincity** [comment]
Hi all, 

I reverted changes from 3.4.0, so 3.4.1 is identical to 3.3.0. 

Thanks,
James
