### ISSUE TITLE
 when we use width="auto" vertical line is visibale to the code area 

### ISSUE THREAD

**Issue by coding-gate** [securingsincity/react-ace#1011]
when we use  width="auto" width is increased but a vertical line is visible on the code area, where earlier scroll bar was displaying  

Here is my code, 
<AceEditor mode={props.state.lang} theme="eclipse" 
                                value={props.state.code} 
                                onChange={(value) => props.updateField( value)} 
                                width="auto"
                                minLines={12} maxLines={12}/>

**Comment by axeldouglas** [comment]
Isn't that the print margin?
Add `showPrintMargin={false}` to see if will "correct" that.

**Comment by Rollins434** [comment]
@axeldouglas  that worked like a charm. I should have checked it sooner.  I ended up doing this css fix.
.ace_print-margin{
   visibility: hidden !important;
}
Thanks for that.
