### ISSUE TITLE
In gutter error icons and warnings are not been displayed in javascript mode after updating to latest version.

### ISSUE THREAD

**Issue by bhargavavarma** [securingsincity/react-ace#1016]
# Problem

In gutter error icons and warnings are not been displayed in Javascript mode after updating to latest version when i have written incorrect statements.

For example, i have used sample HTML code in Javascript mode.
In version 8.0.0, i was able to see the error and warning messages in gutter
![image](https://user-images.githubusercontent.com/54624935/108341373-99734680-71ff-11eb-9031-c16480ad3ffc.png)

In version 9.3.0, i couldnot able to see a single error or warning message in gutter
![image](https://user-images.githubusercontent.com/54624935/108341050-45686200-71ff-11eb-8857-1633b1b350dd.png)

# Expected

Need to show error or warning messages when there is syntax mistake.

**Comment by mukuljainx** [comment]
+1

**Comment by mukuljainx** [comment]
@bhargavavarma did you found the solution?

**Comment by bhargavavarma** [comment]
@mukuljainx it was an issue from my side, so I have closed this issue

**Comment by zhyafe** [comment]
I have the same problem; I solved it through `import 'ace-builds/webpack-resolver';`
