### ISSUE TITLE
readOnly is unused

### ISSUE THREAD

**Issue by wldcordeiro** [securingsincity/react-ace#102]
From reading through the source of react-ace and testing this prop it appears that it is unused. I think it may need to be passed along to ace.

**Comment by jueast08** [comment]
I also noticed this. I took a look in the Ace.jsx file and the loop that attributes the options seems to be in order, yet the readOnly option seems to block.

**Comment by cwtuan** [comment]
readOnly property works fine for me in Chrome. But could it add some disabled style for it?

**Comment by securingsincity** [comment]
I think this may have been fixed since the changes that have been made over the last year.
