### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by IvanSavoskin** [securingsincity/react-ace#1027]
# Problem

Java code validation does not work. I turn on java mode for AceEditor, pass the code, but no errors are highlighted, and when the code changes, the onValidation event simply does not fire. 
How to properly configure everything for validation to work correctly?
ace-builds: 1.4.12;
react-ace: 9.3.0
react: 17.0.1

## Sample code to reproduce your issue
```
<AceEditor
            mode="java"
            theme="github"
            name={props.currentFile.fullPath}
            value={props.currentFile.content}
            height="100%"
            width="100%"
            enableBasicAutocompletion
            enableLiveAutocompletion
            showGutter
            onBlur={() => updateFileContent()}
            onChange={(value) => {
                updateCurrentFile(String(value));
                console.log(value);
            }}
            onValidate={(annotations) => console.log(annotations)}
        />
```

**Comment by PierrickI3** [comment]
@IvanSavoskin did you find out how to do this (validation)?

**Comment by PierrickI3** [comment]
Fixed with this: https://github.com/securingsincity/react-ace/issues/990#issuecomment-779364977
