### ISSUE TITLE
Issue after upgrading to 3.4.0

### ISSUE THREAD

**Issue by SubatomicHero** [securingsincity/react-ace#103]
I get this error using the ace editor:

`index.js:1169 Uncaught TypeError: Cannot read property 'textContent' of null`

Am I missing a property or something?

**Comment by securingsincity** [comment]
Do you mind trying 3.4.1? 3.4.0 had some issues.

**Comment by SubatomicHero** [comment]
Is that available? Github says the latest is 3.4.1

**Comment by securingsincity** [comment]
it should be available now.

**Comment by SubatomicHero** [comment]
Upgrading to 3.4.1 has resolved my issue, thanks.
