### ISSUE TITLE
Maximum call stack

### ISSUE THREAD

**Issue by pnkapadia6** [securingsincity/react-ace#105]
My react component has imported
`import AceEditor from 'react-ace';`

`import 'brace/theme/chrome';`

`import 'brace/mode/css';`

`import 'brace/ext/language_tools';`

and renders
` <AceEditor value={this.getStylesheetValue()}
                    mode="css"
                    theme="chrome"
                    height="400px"
                    width="100%"
                    editorProps={{$blockScrolling: true}}
                    onBlur={this.onBlur}
                    onChange={this.onChange} />`

On typing/pasting, the browser gets stuck and after a while shows this errors - 
`index.js:10431 Uncaught RangeError: Maximum call stack size exceeded`

**Comment by securingsincity** [comment]
Do you mind trying 3.4.1, 3.4.0 had some issues?
