### ISSUE TITLE
Cannot create multiple ace editors in one component

### ISSUE THREAD

**Issue by magicalne** [securingsincity/react-ace#107]
Hey, thanks to provide such a wrapper of ace-editor. Good job.
I have a problem now. Actually I'm new to reactjs. Now I am working on a project with react, redux, material-ui and ace-editor. I really need your help.
When I create two ace-editor in one component, only first one can work. The other one does exist in the source code, but cannot show in the browser. It's very weird to me...

The code looks like:
```html
<div>
<AceEditor />  /**This one works**/

<AceEditor >  /**doesn't work**/
</div>
```

Which part I did it wrong? Or what should I do?
Thanks.:)

**Comment by jueast08** [comment]
Well, if that is exactly how you've written the code, you may want to add at least the attribute name to each tag.

<AceEditor name="some_unique_name1"/>
<AceEditor name="some_unique_name2"/>

Make sure that you take a look at the readme.md for this git as well as how the Ace editor works on the main website. The doc is very well written

**Comment by magicalne** [comment]
@jueast08 well, thanks for your help.
You are right. I just need a name of AceEditor.
