### ISSUE TITLE
ace diff editor

### ISSUE THREAD

**Issue by Waize** [securingsincity/react-ace#112]
Hey,

 I've found the wonderful Ace-Diff-Editor yesterday (https://github.com/benkeen/ace-diff). 
And I wonder if it is possible to merge this function into this react-component. 

Regards,
Waize

**Comment by Waize** [comment]
@securingsincity why is this issue closed? :(

**Comment by securingsincity** [comment]
@Waize I closed it on accident, but I don't think this is going to be on the roadmap anytime soon.

**Comment by nruiz64** [comment]
I agree with @Waize. This is a great library. It would be very nice to include it .

**Comment by simongaviria1** [comment]
Looking into this. Currently using ace-diff editor for a project. Will release an NPM module later this month (April)

**Comment by intrepidOlivia** [comment]
Hello, I am also currently using react-ace and I modified ace-diff's code to work with react-ace in a Split viewer. The component I put together is a rudimentary version of ace-diff and doesn't provide the functionality of clicking to transfer code from one side to the other. But it does highlight the diffed lines using ace editor's markers. Would it be of any benefit for me to add my diff component to this repository?

**Comment by Waize** [comment]
If you start a pr it will be a good start for this feature :)

⁣Mit freundlichen Grüßen, 

Paul Reicherzer​

**Comment by intrepidOlivia** [comment]
Okay, I've started the pull request. I apologize in advance, I am new to contributing to open source so please let me know about my mistakes. I see in the readme for contributing that I am supposed to run tests on my changes, but I don't know how to do that yet. I appreciate any guidance you can give me.

**Comment by intrepidOlivia** [comment]
Can anyone say what the timeline on this is likely to be? Does @securingsincity have to review it?

**Comment by securingsincity** [comment]
@intrepidOlivia thanks for your work. There is couple things that needs to change on the PR. Please make those changes and I can merge. I've been traveling so I haven't had a chance to look at this until today.

**Comment by intrepidOlivia** [comment]
No worries! Take your time, I just wanted to make sure I was navigating everything here correctly. I hope your travels went well.

**Comment by securingsincity** [comment]
This is live in version `6.0.0` !
