### ISSUE TITLE
Allow calling methods on editor.

### ISSUE THREAD

**Issue by captncraig** [securingsincity/react-ace#114]
I have an editor, and some additional navigation components inside a common parent. The idea is, when you click certain buttons, the editor jumps to certain parts of the text. I am doing this in another app by simply calling 

```
editor.find(searchRegex,{
   backwards: false,
   wrap: true,
   caseSensitive: false,
   wholeWord: false,
   regExp: true,
});
```

With this react component, I have no way to access this functionality. It looks like if the `ReactAce` class implemented a `find` method as a passthrough to `editor.find`, I could call that from the parent using react's ref functionality. It feels a bit odd, but it should work.

Would you be against adding such a thing? It would probably be preferable to proxy methods than to just allow access to the editor directly, no?

**Comment by securingsincity** [comment]
I'd be open to a pull request go for it (sorry for the late response) @captncraig

**Comment by drewen** [comment]
ReactAce looks to have an `editor` property, which is the wrapped editor. As you suggested, you could use refs to get to the component, and then you should be able to use the editor on the component to run the function you need:
```
const reactAceComponent = parent.refs.reactAceComponent;
const editor = reactAceComponent.editor
editor.find(searchRegex, {
   backwards: false,
   wrap: true,
   caseSensitive: false,
   wholeWord: false,
   regExp: true,
});
```

As you said, a bit odd, but it should work. Hopefully this helped. If that doesn't work, I can put together a PR to put in that passthrough.

**Comment by lukaszczapiga** [comment]
Why not just expose the editor instance through a callback passed down to the AceEditor component? Then users would have full access to the underlying editor's API.

**Comment by securingsincity** [comment]
@lukaszczapiga that is correct the instance of the editor is available onload but as @drewen mentioned you can access it on the parent component using the `ref`

**Comment by securingsincity** [comment]
This is now documented in the repo in a few ways. I'm going to close this issue.
