### ISSUE TITLE
[FR] implement shouldComponentUpdate

### ISSUE THREAD

**Issue by farfromrefug** [securingsincity/react-ace#115]
i have some issues with that component because it's redrawn on every setState even if the editor actually does not need an  update.
This is because `shouldComponentUpdate` is not implemented as explained [here](https://facebook.github.io/react/docs/component-specs.html#updating-shouldcomponentupdate)

Here is an example of implementation
https://github.com/Lapple/react-json-inspector/blob/master/json-inspector.js

**Comment by benjamine** [comment]
I'm giving this one a try if you don't mind

**Comment by securingsincity** [comment]
@benjamine go for it!

**Comment by farfromrefug** [comment]
Thanks will try it as soon as possible
