### ISSUE TITLE
Auto completion working but enableSnippets not working

### ISSUE THREAD

**Issue by polodev** [securingsincity/react-ace#116]
I enable all options. auto completion working but snippets not working. How can i enable snippets in react ace
`setOptions={{
    enableBasicAutocompletion: true,
    enableLiveAutocompletion: true,
    enableSnippets : true,
    tabSize: 4,
    fontSize: 14,
    showGutter: true
}}`

**Comment by sgentile** [comment]
Was curious if any progress has been made implementing snippet support ?  I have an external snippet file (json) I want to use - would like any guidance on setting that up with this component.

**Comment by securingsincity** [comment]
Wow I apologize for not getting back to you sooner. Looking at the codebase that is not implemented because it may be missing a setting on the Ace side  `ace.require("ace/ext/language_tools");` #119 looks like the same issue. Will need to investigate further.

**Comment by naivefun** [comment]
Is there a way to add snippets dynamically?
