### ISSUE TITLE
onChange swallows event

### ISSUE THREAD

**Issue by smith-kyle** [securingsincity/react-ace#118]
Ace passes an event into every onChange callback that contains details of the exact change that occurred but [in react-ace](https://github.com/securingsincity/react-ace/blob/master/src/ace.jsx#L143) the event is not passed into the onChange but instead the value of the editor is passed along. 

To keep react-ace consistent with ace would you be open to instead pass the event passed into onChange into `react-ace`'s `this.props.onChange` callback?

**Comment by sandaemc** [comment]
👍

**Comment by securingsincity** [comment]
@smith-kyle would be open to a PR on this. I want to apologize for only getting back to this now, I shouldn't be ignoring this project the way I have.

**Comment by pnkapadia6** [comment]
@securingsincity Hey, I could send in a PR for this. Do we want to replace the value passed with the event? or add the event as another parameter?
