### ISSUE TITLE
Does enableSnippets work?

### ISSUE THREAD

**Issue by voronianski** [securingsincity/react-ace#119]
I have option enabled but it doesn't seem to work.. 

``` js
<Ace
    name="codeEditor"
    mode="jsx"
    theme="tomorrow"
    value={code}
    tabSize={tabSize}
    width="auto"
    height="auto"
    onChange={this.handleChange('onCodeChange')}
    showPrintMargin={false}
    editorProps={{$blockScrolling: Infinity}}
    enableBasicAutocompletion={true}
    enableSnippets={true}
    enableLiveAutocompletion={true}
/>
```

**Comment by securingsincity** [comment]
Wow I apologize for not getting back to you sooner. Looking at the codebase that is not implemented because it may be missing a setting on the Ace side  `ace.require("ace/ext/language_tools");`

**Comment by andyforever** [comment]
@securingsincity Does this [brace wiki page](https://github.com/thlorenz/brace/wiki/Advanced:-Accessing-somewhat-hidden-ACE-features) help with this problem?
