### ISSUE TITLE
Annotations get removed if a newline is added

### ISSUE THREAD

**Issue by Poltergeist** [securingsincity/react-ace#129]
If one adds an annotations as a prop to the react ace component. They only get shown until I add a newline to the value. To show that problem I changed the example. The only thing I changed is adding annotations to the `example/index.js` in line `29`. `annotations={[{ row: 5, column: 2, type: 'error', text: 'Some error.'}]}`.
I got it to work if I put the render on line `24` into a function and call that function with the `newValue` Full change starting on line `19`

``` JS
function onChange(newValue) {
  console.log('change', newValue);
  renderFirst(newValue);
}

function renderFirst(value = '') {
  // Render first editor
  render(
    <AceEditor
      mode="java"
      theme="github"
      name="blah1"
      value={value}
      annotations={[{ row: 5, column: 2, type: 'error', text: 'Some error.'}]}
      height="6em"
      onChange={onChange}
    />,
    document.getElementById('example')
  );
}

renderFirst();
```

![react-ace-annotations mov](https://cloud.githubusercontent.com/assets/156010/16838831/c662c5dc-49cb-11e6-9d5e-b8b30c6b7e58.gif)

I hope the description is clear, and I hope this is not me using the component wrong. Thanks in advance.

**Comment by securingsincity** [comment]
@Poltergeist did @leMaik 's advice fix the issue

**Comment by leMaik** [comment]
Well, it fixed the very same issue for me. :wink:

**Comment by Poltergeist** [comment]
Sadly I never got back to test it, I try to test it asap.

Maik Marschner <notifications@github.com> schrieb am Fr., 23. Sep. 2016 um
14:46 Uhr:

**Comment by NishaUttawani** [comment]
I am getting the expected annotations  but the hover effect is not there. 
It displays nothing when I hover over the cross, no "text"

**Comment by securingsincity** [comment]
In latest version `4.2.3` using the example, I am unable to reproduce this bug. I believe it's been resolved.

**Comment by mikolajpp** [comment]
Sadly, I am reproducing it again.
I have this code:
```
  editor.$useWorker = false;
```
Whenever cursor leaves or enters the line with custom annotation added, the annotation vanishes. 

Cursor can move freely and even add newlines without touching the annotated line. Once it hits it, the annotation disappears.

**Comment by abrarmahmood** [comment]
Is there any update on this? I am experiencing the same issue as described by @mikolajpp Thanks

**Comment by nurpax** [comment]
I have this problem too.  @abrarmahmood, @mikolajpp did you ever figure out why this is happening?  The various ways of setting useWorker=false did not work for me.

**Comment by daid** [comment]
You need to set the $useWorker on the session:
```
editor.session.$useWorker = false;
```

**Comment by hamoody-omar** [comment]
I am wondering if there is a way around this because setting useWorker = false disables ace syntax checking and that's not what I want. I want to merge my annotations to the ace's ones.

**Comment by aplishka** [comment]
@hamoody-omar The following answer allows you to use custom annotations alongside the Workers annotations: https://github.com/securingsincity/react-ace/issues/483#issuecomment-493821013
