### ISSUE TITLE
Custom commands with ArrowUp and ArrowDown as key bindings

### ISSUE THREAD

**Issue by gusaiani** [securingsincity/react-ace#1299]
Hello all,

thank you very much for React Ace.

I'm trying to control a custom autosuggestion component so that, when a user presses the up/down arrow keys and the autosuggestions are open, they navigate suggestions.

My current approach has been to try a custom command like below:

```js
<AceEditor
  commands={[
    {
      name: "commandName",
      bindKey: { win: "ArrowDown", mac: "ArrowDown" },
      exec: () => {
        console.log("🚀, key-binding used");
      },
    },
    {
      name: "save",
      bindKey: {
        win: "Ctrl-enter",
        mac: "Cmd-enter",
      },
      exec: () => {
        console.log("🚀, key-binding used ctrl-enter");
      },
    },
  ]}
…
 />
```

The Cmd-enter command works fine.
The ArrowDown command does not.

Any idea what I'm doing wrong?

**Comment by nightwing** [comment]
Ace uses Up and Down for these key names without the Arrow part

**Comment by gusaiani** [comment]
Ah gotcha. Will try that, thank you for the answer.
