### ISSUE TITLE
Problems with rendering using preact-compat instead of React

### ISSUE THREAD

**Issue by voronianski** [securingsincity/react-ace#130]
- https://github.com/developit/preact-compat
- reproduce via https://github.com/voronianski/react-ace-preact-compat-issue

The problem appeared when I wanted to port https://esnextb.in from React to Preact in order to reduce bundle size. Unfortunately it's not possible now due to this issue (https://github.com/voronianski/esnextbin/pull/27).

**Comment by securingsincity** [comment]
I likely won't be able to support preact anytime soon, but i'm happy to take a pr if you or anyone else can figure this one out.

**Comment by securingsincity** [comment]
@voronianski please check out https://github.com/securingsincity/react-ace-preact-example which should show how to use preact-compat with react-ace
