### ISSUE TITLE
Infinite loop when feeding in value from onChange

### ISSUE THREAD

**Issue by njlr** [securingsincity/react-ace#133]
I want to use the `value` of an `AceEditor` component in other components, so I need to use the callback `onChange`. However, I also need to set the value from other components, so I need to pass it in via props. This is a common pattern for input fields in React. 

For example: 

```
render() {
  const onChange = (value) => {
    this.setState({value});
  };
  return(
      <AceEditor
        name='File'
        value={this.state.value}
        onChange={onChange} />);
}
```

This seems to enter an infinite loop. 

Perhaps the `AceEditor` is firing the `onChange` event incorrectly?

**Comment by j8** [comment]
@njlr did you managed to update the value to the editor?

**Comment by njlr** [comment]
@j8 Yes, [my fork](https://github.com/njlr/react-ace) supports the above example.

**Comment by j8** [comment]
Thank. I managed to update the value from external component by putting 'ref' property in the editor. For example:

```js
                    <AceEditor
                      mode="javascript"
                      theme="github"
                      ref={(c) => this.addDeviceModalComponent = c}
                      name="addDeviceEditor"
                      editorProps={{$blockScrolling: true}}
                      value={this.deviceConfig}
                      onChange={this.onChange}
                    />
```

And update the value using:

```js
        this.jsonBody = {
            name: '',
            configuration: {
                test: 123
            }
        }
        this.deviceConfig = `${JSON.stringify(this.jsonBody, null, '\t')}`
        this.addDeviceModalComponent.editor.setValue(this.jsonBody, 1)
```
