### ISSUE TITLE
ace.config.set('basePath', 'path') cdnjs

### ISSUE THREAD

**Issue by dlv-dls2** [securingsincity/react-ace#1337]
I'm creating an HTML project with the ace editor (cdnjs) but I can't set the theme and mode because of `Unable to infer path to ace from script-src, use ace. config.set('basePath', 'path') to enable dynamic loading of modes and themes or with webpack use ace/webpack-resolver` error. Can you please help me? 🙏

**Comment by dlv-dls2** [comment]
Wait, wrong repo. Sorry

**Comment by zjtt** [comment]
Is it solved?
