### ISSUE TITLE
keyboardHandler - vim/emacs

### ISSUE THREAD

**Issue by mukeshsoni** [securingsincity/react-ace#134]
I am not able to get the keyboardHandler prop to work. This is what i have tried - 

```
import 'brace/keybinding/emacs'
import 'brace/keybinding/vim'

// inside render somwhere
<AceEditor
         keyboardHandler='vim' />
```

vim mode is not activated. Do i need to import anything else?

**Comment by mukeshsoni** [comment]
I finally used `editor.setKeyboardHandler('ace/keyboard/vim')`

**Comment by veeramarni** [comment]
Try `require('brace/keybinding/vim'); `instead of `import`
