### ISSUE TITLE
Can't seem to get annotations to show up 

### ISSUE THREAD

**Issue by balthatrix** [securingsincity/react-ace#138]
Not sure if this is an issue, or I'm just doing it wrong.  This is what I see as my editor: 
![ace_editor_no_annotations](https://cloud.githubusercontent.com/assets/5818492/18722808/f79c6360-7fea-11e6-8b40-64f64c001245.png)

You would expect there to be a an error notation on line 5, since this is my render method (hardcoded with an annotation on line 5):
EDIT: uggh, code paste in wyswyg doesn't like jsx I guess.  Here's a screencap of render code:
![image](https://cloud.githubusercontent.com/assets/5818492/18723079/1533d56a-7fec-11e6-884d-95f5bbb942cd.png)

I was also unable to get markers to work.

**Comment by parthms** [comment]
@balthatrix - Here's how I got markers working.

Assuming you use the 'error-marker' class like in docs, make sure the define the following style for it:
`position: absolute`.

By adding the style above, markers work but only for rows. If you provide a starting column and ending column, the calculations are slightly messed up. Either way at least the row highlighting will work for you as expected.

**Comment by emmaccacca** [comment]
Do you solve your problem? I have encoured into the same question and I can't solve it.
