### ISSUE TITLE
plugin not found

### ISSUE THREAD

**Issue by AnjaP7** [securingsincity/react-ace#139]
I installed version 3.6.0. It expects a plugin which isn't installed after calling npm install.

The error:
Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "/Users/aporedda/_Dev/BitBucket/scalehub/CloudPlatform/Modules/node-js-modules/service-designer/node_modules/react-ace/package.json"

**Comment by securingsincity** [comment]
Using the latest version of react-ace this shouldn't happen.
