### ISSUE TITLE
Add testing framework and testing

### ISSUE THREAD

**Issue by securingsincity** [securingsincity/react-ace#140]
This project was definitely made in haste early on and skipped adding a testing framework. Would love to add some unit tests to make sure we don't break anything in future builds.

**Comment by schenkfab** [comment]
Hi @securingsincity I would really like to take this one but I might need some time as I'm not that advanced yet.

**Comment by jleajones** [comment]
@securingsincity @schenkfab , I'd like to help.

**Comment by williamcabrera4** [comment]
Hello @schenkfab @jleajones 
Is this issue still available or in development?

Thanks

**Comment by schenkfab** [comment]
@williamcabrera4  Don't know. Still waiting for feedback from the maintainer about the issue assignment, but not sure if this project is still maintained. Therefor, go for it, I'm out :)

**Comment by securingsincity** [comment]
hi @schenkfab i don't usually do formal assignments for issues, feel free to contribute as you see fit.

**Comment by williamcabrera4** [comment]
Pull Request with test
https://github.com/securingsincity/react-ace/pull/146

**Comment by securingsincity** [comment]
awesome thanks @williamcabrera4
