### ISSUE TITLE
Cannot read property 'acequire' of undefined

### ISSUE THREAD

**Issue by mathisonian** [securingsincity/react-ace#141]
Hey,

Thanks for the library. I'm trying to use this with webpack (I'm really just trying to put it in a barebones app created with `create-react-app`). Looking at your webpack example I can't find any differences that would be causing this error, but maybe I am missing something obvious. Screenshots of the error attached below

<img width="607" alt="screen shot 2016-10-05 at 1 06 04 pm" src="https://cloud.githubusercontent.com/assets/1074773/19129553/8d8e829c-8afc-11e6-8ebb-06ab94297a91.png">
<img width="631" alt="screen shot 2016-10-05 at 1 06 09 pm" src="https://cloud.githubusercontent.com/assets/1074773/19129559/8f27f368-8afc-11e6-80ab-9f7535b93650.png">

**Comment by mathisonian** [comment]
I have no idea what was causing this... `rm -rf node_modules` didn't fix the issue but nuking the whole project and recloning did ¯\_(ツ)_/¯

**Comment by avizaviz** [comment]
happens to me too, no simple way to resolve it?

**Comment by garetmckinley** [comment]
+1

**Comment by darlingtld** [comment]
I bumped into the same issue.  Got no idea how to fix this.

**Comment by MVMS1994** [comment]
+1

**Comment by mathisonian** [comment]
re-opening since it seems others are having the same issue

**Comment by securingsincity** [comment]
Hi all, as of `4.1.6` creat-react-app should work. https://github.com/securingsincity/react-ace-create-react-app-example as an example

**Comment by nicholasareed** [comment]
Any idea what actually causes this though? I'm trying to use react-ace in a larger project and I'm getting this error. Clearing node_modules didn't help. React 15.4.2

**Comment by callmeaatrey** [comment]
I am getting the same error even though I am using `4.2.0` version. I removed everything and am just importing the two things i.e.

`import AceEditor from 'react-ace';`
`import brace from 'brace';`

Error:
`Uncaught TypeError: Cannot read property 'acequire' of undefined `

But, still it says the same old thing.  How do I fix this?

**Comment by jefflewis** [comment]
I am getting this on V5.0.1. I've destroyed node_modules, cleared yarn cache, reinstalled modules with yarn, and still get this error. The _simplest_ hello world app will fail if I try to `import AceEditor from 'react-ace'` in the file.

@securingsincity  What should I look for in trying to get this to work? Is this some sort compilation error with brace/react-ace?

I get the same error if I try to directly include the compiled JS file:`import AceEditor from '../node_modules/react-ace/dist/react-ace.js'`

**Comment by missing1984** [comment]
Ran into the same issue. 'brace' rely on global variable (window.ace) and it will fail if there's already a window.ace variable in the page. Make sure you only import ace once.

**Comment by m1n0s** [comment]
Faced totally same issue while deploying it to production through `create-react-app`.
I mean that locally it works totally great but after deploying with CI - I see this error
`ace.js:37 Uncaught TypeError: Cannot read property 'acequire' of undefined`
![image](https://user-images.githubusercontent.com/12004923/43010561-6f9d5a56-8c49-11e8-84b7-26e429809c9e.png)
![image](https://user-images.githubusercontent.com/12004923/43010579-7aba00b0-8c49-11e8-8a78-488e85d4d4cc.png)

```
"brace": "^0.11.1",
"react": "^16.4.0",
"react-ace": "^6.1.4",
"react-dom": "^16.4.0",
```

Any ideas how to fix it?

**Comment by m1n0s** [comment]
I've tried to build a production build in `create-react-app` locally and can reproduce the issue. 
The `window.ace` is undefined after a successful build.

**Comment by pdubey84** [comment]
Am stuck on this :( did anyone resolve this?
