### ISSUE TITLE
Brace as peer dependency

### ISSUE THREAD

**Issue by k15a** [securingsincity/react-ace#142]
Hey,

wouldn't it be better to have brace as a peer dependency as well because it has to be installed anyway?

**Comment by mpj** [comment]
Peer dependencies are evil as hell and should only be used if you absolutely must have a single, global reference of a specific version for your module to work.

**Comment by securingsincity** [comment]
@k15a @mpj agree peer dependency is probably the wrong direction. However changing the webpack build so that brace is an external dependency isn't. I'd be really reluctant to change it without a full version bump as it's a big change for those using it today.

**Comment by mertkahyaoglu** [comment]
Not 100% related to this issue, but I would like to ask. Should we really import `brace` in order to use React Ace? Because removing the import didn't really seem to change anything but decreased the bundle size by ~300kb

**Comment by larrydahooster** [comment]
Can anyone help me with this? react-ace just hit me with 600kb of js. Whereas the biggest chunk comes from brace. I need to include it as my own dependency though react-ace already includes it. Am I missing a point? Sorry for commenting on this closed issue. 

![screen shot 2017-04-25 at 12 08 25](https://cloud.githubusercontent.com/assets/4989851/25380494/a63b872e-29b0-11e7-9178-ca2f4af8393c.png)
