### ISSUE TITLE
React 18: Cannot read properties of undefined (reading 'destroy')

### ISSUE THREAD

**Issue by ttessarolo** [securingsincity/react-ace#1464]
I've upgraded my app to React 18 and I'm getting:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'destroy')
```
every time react-ace editor is unmounted.

I saw this PR:

https://github.com/securingsincity/react-ace/pull/1293 

when it will be merged?

Thanks!

**Comment by crow7m** [comment]
+1

**Comment by crow7m** [comment]
@securingsincity Hi, may i ask if there is a plan to merge in the PR mentioned above? than you

**Comment by skye-levit** [comment]
+1

**Comment by rongQwak** [comment]
+1

**Comment by israelaqwak** [comment]
+1

**Comment by ttessarolo** [comment]
Meanwhile I just mediaset grated to: https://github.com/suren-atoyan/monaco-react

an active repo with many pros (few cons) but zeros refactoring.

**Comment by securingsincity** [comment]
This should be fixed in version 10 https://github.com/securingsincity/react-ace/releases/tag/v10.0.0
