### ISSUE TITLE
PureComponent is only in React v16-alpha ?

### ISSUE THREAD

**Issue by ponelat** [securingsincity/react-ace#156]
Just updated, got errors about `ace.js:29 Uncaught TypeError: Super expression must either be null or a function, not undefined`

It looks like my version of React doesn't export `PureComponent`... but then I tried to find the version of React that shipped with it... https://github.com/facebook/react/blob/c8fbdac22717e91d1f1638a932eed3ce4cc39ff7/package.json#L4

I think React v16-alpha is a little edgy? One could just use a shallow-compare, or similar for now...

**Comment by victorisildur** [comment]
Encountered the same problem

**Comment by levi0913** [comment]
i tried add  "_PureComponent ? _PureComponent = _PureComponent : _PureComponent = null;" in ace.js ,it looks fine; 

could ace team add the judge logic ?

**Comment by securingsincity** [comment]
Reverted back to Component. too many issues were being created by using PureComponent.
