### ISSUE TITLE
package brace need to upgrade to 0.9.1

### ISSUE THREAD

**Issue by cuining** [securingsincity/react-ace#164]
[detail](https://github.com/thlorenz/brace/pull/73)

**Comment by mayuelei66** [comment]
when use react-act 4.1.0, I found a Chinese input bug in brace v0.8, when upgrading to 0.9.1,  the problem solved.

**Comment by cuining** [comment]
@mayuelei66  I replace react-ace with react-codemirror, it's smaller than react-ace.

**Comment by mayuelei66** [comment]
@cuining 多谢，我美团的。。

**Comment by cuining** [comment]
@mayuelei66 哈哈 好巧

**Comment by securingsincity** [comment]
@cuining @mayuelei66 @chentsulin thanks should be all set. 

I agree this library is huge ultimately I would like to see a better react code editor built that doesn't rely on code mirror or ace. I haven't had the opportunity to start the project but it is a goal of mine in 2017.
