### ISSUE TITLE
height doesn't update

### ISSUE THREAD

**Issue by zwhitchcox** [securingsincity/react-ace#166]
Is there anyway to update the height of the react editor programmatically? I am listening for a window resize event, and I pass in the correct height, but the ace editor height does not adjust, even when it's passed in a different height.

I also tried getting the reference to the editor and using `editor.resize()`, but even that doesn't work.

**Comment by zwhitchcox** [comment]
Nevermind, got it to work...turns out, I wasn't updating the component

**Comment by jyek** [comment]
For benefit of others with this issue, say your component is `<AceEditor ... ref="reactAceEditor" />`, you have to do `this.refs.reactAceEditor.editor.resize()` to update height
