### ISSUE TITLE
Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by no1melman** [securingsincity/react-ace#175]
I'm get this error
```
Super expression must either be null or a function, not undefined
```

Its stack trace points to this line:

    var ReactAce = function (_PureComponent) {
        _inherits(ReactAce, _PureComponent);

The source map says this line from `ace.jsx`:

    import ace from 'brace';
    import React, { PureComponent, PropTypes } from 'react';
    import isEqual from 'lodash.isequal'; <-------------- HERE

Why am I getting this? I've setup the webpack config like so:

```
import webpack from 'webpack';
import path from 'path';

const reactAcePath = path.join(__dirname, './node_modules/react-ace/src/ace.jsx');

export default {
    debug: true,
    devtool: 'inline-source-map',
    noInfo: false,
    entry: {
        app: [
            'eventsource-polyfill', // hot reloading with IE
            'webpack-hot-middleware/client?reload=true', // reloads the page if hot module reloading fails
            'isomorphic-fetch',
            path.resolve(__dirname, './web/index')
        ],
        login: [
            'eventsource-polyfill', // hot reloading with IE
            'webpack-hot-middleware/client?reload=true', // reloads the page if hot module reloading fails
            'isomorphic-fetch',
            path.resolve(__dirname, './web/login')
        ]
    },
    target: 'web',
    output: {
        path: __dirname + '/dist',
        publicPath: '/',
        filename: '[name].bundle.js'
    },
    devServer: {
        contentBase: path.resolve(__dirname, './web')
    },
    resolve: {
        alias: {
            'react-ace': reactAcePath
        }
    },
    plugins: [
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin()
    ],
    module: {
        loaders: [
            {test: /\.(js|jsx)$/, include: [reactAcePath, path.join(__dirname, 'web')], loaders: ['babel']},
            {test: /(\.css)$/, loaders: ['style', 'css']},
            {test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: 'file'},
            {test: /\.(woff|woff2)$/, loader: 'url?prefix=font/&limit=5000'},
            {test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=100000&mimetype=application/octet-stream'},
            {test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=100000&mimetype=image/svg+xml'},
            {test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000&minetype=application/font-woff" },
            {test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader" }
        ]
    }
};
```

**Comment by no1melman** [comment]
Also, isn't there already a compiled version `dist/`, why can't we use that?

**Comment by securingsincity** [comment]
@no1melman i'm curious why you are pointing directly at `src/ace.jsx` and not using es5 umd output in `lib` which is the main entry point for npm or the `dist` es6 one?

**Comment by no1melman** [comment]
@securingsincity i was following the example folder...

**Comment by no1melman** [comment]
So I removed all the ace specific configuration from the webpack. I just used:

```
import AceEditor from 'react-ace';

import 'brace/mode/java';
import 'brace/theme/github';

```

And I'm getting this error still ....

**Comment by no1melman** [comment]
@securingsincity it says that at this line:

```
var ReactAce = function (_PureComponent) {
    _inherits(ReactAce, _PureComponent);
```

where `_PureComponent` is `undefined`....

**Comment by securingsincity** [comment]
OK being completely honest I didn't really review the example folder and it was quite broken see: #150 #173. It seems that pointing `ace.jsx` doesn't resolve `react` or `react-dom` which are the problems you are seeing. In the latest master build, you use the npm as intended by the main, rather than trying to resolve it using by webpack.

**Comment by no1melman** [comment]
@securingsincity what do you mean by 

> In the latest master build, you use the npm as intended by the main, rather than trying to resolve it using by webpack.

Are you saying use `<script src="react-ace.js">` or are you saying just use the `import AceEditor from 'react-ace';`

**Comment by securingsincity** [comment]
Pushing up a change in 4.1.6 to resolve this issue. It has to do with `PureComponent` which simply won't support older versions of react.

**Comment by no1melman** [comment]
I am using 

```json
{
    "react": "15.0.2",
    "babel-cli": "^6.18.0",
    "babel-core": "^6.18.2",
}
```

**Comment by securingsincity** [comment]
yup @no1melman you'll need to upgrade to `4.1.6` it will fix your issue. if you look at https://github.com/securingsincity/react-ace-create-react-app-example or https://github.com/securingsincity/react-ace-webpack-example or the new example folder. It shows a number of ways you can include react-ace, build it and get it working.
