### ISSUE TITLE
How can I get selected text in Ace editor?

### ISSUE THREAD

**Issue by terryureche** [securingsincity/react-ace#177]
@ tried to set an event for select in onLoad but without success

**Comment by sush03** [comment]
> onselectionchange returns a event.How do you get the text that has been selected

@vig7 Where you able to solve this ?

**Comment by vig7** [comment]
> > onselectionchange returns a event.How do you get the text that has been selected
> 
> @vig7 Where you able to solve this ?

yes,  this.refs.aceEditor.editor.getSelectedText() will get you the text
