### ISSUE TITLE
JSON mode shows the json in one line.

### ISSUE THREAD

**Issue by shatyajeet** [securingsincity/react-ace#180]
`import 'brace/mode/json';`
`<ReactAce mode='json' value={JSON.stringify(jsonObject)} theme='github' />`

The entire json is shown in 1 line and with no formatting.

What option should enable formatting of the jsonObject?

**Comment by shatyajeet** [comment]
Scratch that. `JSON.stringify(jsonObject, null, 2)` solves it.

**Comment by phping1** [comment]
I met the same problem，thks!

**Comment by id0Sch** [comment]
@shatyajeet Correct me if im weong but this is what i got for
``` javascript
<AceEditor
            mode="json"
            theme="github"
            name={floatingLabelText}
            value={JSON.stringify(value,null,2)}
            height='100px'
            width='100%'
            onChange={onChange}
            editorProps={{
                $blockScrolling: false,
            }}
        />
```
![image](https://user-images.githubusercontent.com/5864772/32121640-122d94c6-bb66-11e7-9ca0-a02a4296bf78.png)

in comparison to
``` javascript
<AceEditor
            mode="json"
            theme="github"
            name={floatingLabelText}
            value={value}
            height='100px'
            width='100%'
            onChange={onChange}
            editorProps={{
                $blockScrolling: false,
            }}
        />
```
![image](https://user-images.githubusercontent.com/5864772/32121659-327f3b8a-bb66-11e7-8b19-10a5d2daf769.png)

**Comment by chriswatts91** [comment]
@id0Sch Is `value` a string? If so you could try parsing it first: `JSON.stringify(JSON.parse(value), null, 2)`

**Comment by id0Sch** [comment]
correct, my bad!

**Comment by Nashorn** [comment]
> @id0Sch I think `value` is a string? If so you could try parsing it first: `JSON.stringify(JSON.parse(value), null, 2)`

Works perfect:
editor.setValue(JSON.stringify(JSON.parse(jsonStr), null, 2))
