### ISSUE TITLE
Why swallow errors/missing imports in props

### ISSUE THREAD

**Issue by mjmdavis** [securingsincity/react-ace#182]
Wouldn't it be better if react-ace didn't swallow these error messages? It can lead to confusing behavior when trying to enable certain features without the correct imports.

https://github.com/securingsincity/react-ace/blob/master/src/ace.jsx#L88

**Comment by securingsincity** [comment]
@mjmdavis do you have any ideas on how we would want to implement this?

**Comment by securingsincity** [comment]
This is fixed in version `5.0.0` it will add a `console.warn` on wrong imports
