### ISSUE TITLE
How to call for Redo and Undo?

### ISSUE THREAD

**Issue by CasperHK** [securingsincity/react-ace#183]
How to call for Redo and Undo in react-ace? Any idea for implementing it?

**Comment by securingsincity** [comment]
If you give an instance of `react-ace` a ref for example `editor` then you can access the underlying functionality of ace from outside of react-ace by calling `editor` on that instance of `react-ace`. To do something like undo or redo you can do on the parent component:

```
         <button onClick={()=> {
             this.refs.editor.editor.undo()
           }}>Undo</button>
           <button onClick={()=> {
             this.refs.editor.editor.redo()
           }}>Redo</button>
```
