### ISSUE TITLE
Uncaught TypeError: Cannot read property 'acequire' of undefined

### ISSUE THREAD

**Issue by callmeaatrey** [securingsincity/react-ace#187]
I am getting the same error even though I am using 4.2.0 version. I removed everything and am just importing the two things i.e.

`import AceEditor from 'react-ace';`
`import brace from 'brace';`

Error:
`Uncaught TypeError: Cannot read property 'acequire' of undefined`

But, still it says the same old thing. How do I fix this?

PS: I even tried your example component as a substitute that you talked about in @securingsincity  just to see if it works; but unfortunately it didn't! I hope you might be able to help soon. 

BTW, this is a similar issue to [#141](https://github.com/securingsincity/react-ace/issues/141).

**Comment by SidneyNemzer** [comment]
For anyone having this issue:

I experienced this myself. I'm not sure, but it seems that deleting the contents of the `node_modules` folder then re-running `npm install` fixed it

I didn't have to modify my webpack config to fix it.
