### ISSUE TITLE
i get some error in the project

### ISSUE THREAD

**Issue by abnerCrack** [securingsincity/react-ace#189]
material：[i used](https://github.com/alexkrolick/preact-photon-electron-quick-start)
```
Error
Could not load worker TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
```

**Comment by securingsincity** [comment]
Hi @abnerCrack, react-ace does not support preact per #130.

**Comment by securingsincity** [comment]
@abnerCrack you can check out an example of how to use preact with react-ace here: https://github.com/securingsincity/react-ace-preact-example
