### ISSUE TITLE
Publish code as ES5

### ISSUE THREAD

**Issue by yamalight** [securingsincity/react-ace#19]
Would you consider publishing the resulting code as plain ES5 module? 
Pre-compilation of node_modules in big projects usually does not works too well so it's better to publish ES5 code as main entry point.

I'd [forked the repo](https://github.com/eccenca/react-ace) and re-written the code to compile to ES5 as prepublish step (we use it in our current project now), so you can have a look at example implementation there. I'd also used some of my helper libs, so it's a bit too many changes to make PR, but maybe you can consider just switching to publishing ES5.
Thanks!

**Comment by andrerpena** [comment]
I second that.. and @yamalight , I'm gonna give your version a try

**Comment by securingsincity** [comment]
This should be fixed in 2.0.2.
