### ISSUE TITLE
defaultValue disappear after seconds since creation.

### ISSUE THREAD

**Issue by wellbeck190** [securingsincity/react-ace#193]
```
<AceEditor
   mode="javascript"
   theme="xcode"
   name="linkEditor"
   width="100%"
   height="100%"
   defaultValue="let msg='disappear after seconds since creation';"
   editorProps={{$blockScrolling: true}}
/>
```
Everything worked correctly, defaultValue appeared. But disappear after seconds since creation.
I tested with react-ace@4.2.2, chrome 57.
I check defaultValue in React Devtools isn't empty.
Help me!

**Comment by securingsincity** [comment]
@wellbeck190 I think you may be having other issues. I just tried this locally and had no issue. Perhaps some other component is causing a rerender - check out https://github.com/garbles/why-did-you-update for help
