### ISSUE TITLE
Creating a split editor

### ISSUE THREAD

**Issue by niki-m** [securingsincity/react-ace#203]
Is there a way to split the editor horizontally/vertically?

I've tried importing 'brace/ext/split', but the split api does not seem to be available.

A clone of the kitchen sink demo for react-ace would be very helpful with this problem,

**Comment by securingsincity** [comment]
I don't think anyone has tried it @niki-m  but it would be a necessary addition to add support for #112 . I'll look at this when I have time. If you are able to find a solution I'd be very open to a PR.

**Comment by niki-m** [comment]
I used Ace directly a few years back & from what I remember, you have to use the split api to create the editor instance (usaual way won't work).

Looking to see if brace itself is capable of it.

**Comment by securingsincity** [comment]
Looks like https://github.com/thlorenz/brace/issues/83 is related to this issue.

**Comment by niki-m** [comment]
Got the Split API loaded using the following: 

`import 'brace/ext/split'
brace.acequire(['ace/split'], function(s) { brace.Split = s.Split; })`

Now to try and use it...

**Comment by niki-m** [comment]
Right, I have no experience with github pull requests, but here's the lines to add: 

(after) const { Range } = ace.acequire('ace/range');
+ import 'brace/ext/split'
+ const { Split } = ace.acequire('ace/split');

---

(after)    if(markers && markers.length > 0){
      this.handleMarkers(markers);
    }

+    var split = new Split(this.editor.container,`ace/theme/${theme}`,1)
+    this.editor.env.split = split;

(before)    // get a list of possible options to avoid 'misspelled option errors'

**Comment by niki-m** [comment]
To use from onLoad (taken from the kitchen sink demo): 

			var sp = editor.env.split;
			var value = "below"

			var newEditor = (sp.getSplits() == 1);
			sp.setOrientation(value == "below" ? sp.BELOW : sp.BESIDE);
			sp.setSplits(2);

			if (newEditor) {
				var session = sp.getEditor(0).session;
				var newSession = sp.setSession(session, 1);
				newSession.name = session.name;
			}

**Comment by niki-m** [comment]
The session isn't cloned properly at the moment, but at least the editor is split now.

**Comment by niki-m** [comment]
Update: Fixed the cloning issue.  Instead of setting a value in the AceEditor component, you have to wait for the instance to load (onLoad) and then set the value from there.  

Have edited the example onLoad function above.

**Comment by niki-m** [comment]
Right.  All done.  Have removed half the comments & fixed the cloning issue in the main source.

List of changes is (hopefully) final now & the example is working fine.  Was the editor.setValue line that was causing problems as that was the bit that needs to be handled by the split api.

**Comment by securingsincity** [comment]
@niki-m this was very helpful. Sounds like we need another component, in addition to the main component. I'll create a more defined issue related to this one and have it be part of the next major version of `react-ace`

**Comment by niki-m** [comment]
Just tried to get on with my project with these modifications & there's a few problems now.

Auto-completion & syntax highlighting isn't working.  I think the editor is going to need a complete re-write for the split api.

**Comment by securingsincity** [comment]
Yup I imagine it needs it's own component. I've marked it out as a new feature for `v5.0`. I'll start work on this this week.

**Comment by niki-m** [comment]
I've been making quite a few changes & the only thing that doesn't seem to be working at the moment is auto-completion in the split display.  Everything seems to work fine in the main display.

To make sure your code isn't polluted, I've forked it here:

[https://github.com/niki-m/react-ace](Forked react-ace)

**Comment by securingsincity** [comment]
@niki-m I started work on the split editor. It's mostly working in its own example. In the work I'm doing each can have separate values and is able to set the number of splits and orientation dynamically. Feel free to check it out here #205

**Comment by niki-m** [comment]
Looking good.  Can't wait to see the final release!

I keep running into issues on my fork like the following editor showing real-time diffs..  There's a line on the second pane that won't go away.   Works enough for the moment though.

![split-diff](https://cloud.githubusercontent.com/assets/5882248/26402473/71f005b0-4082-11e7-858b-5ab6e786aa2f.png)

**Comment by securingsincity** [comment]
that line is the print margin. my latest commit removes that line. but still allows for a print margin per editor

**Comment by securingsincity** [comment]
Ok this live as part of `5.0.0` You can check out the documentation. All of the bugs you described above should be fixed.
