### ISSUE TITLE
react-ace in resizable container

### ISSUE THREAD

**Issue by MartinHaeusler** [securingsincity/react-ace#207]
I am trying to use `react-ace` inside a `div` that can be resized by the user at runtime (to be precise, the size of the `div` is controlled by a `flexbox`). By default, the ACE editor requires fixed with and height values in pixels. 

By using [react-measure](https://github.com/souporserious/react-measure) and some `div` nesting, I was able to get the ACE Editor to resize its bounds correctly, at least visually. However, the controls inside the editor (e.g. the width of the line wrapping, the scroll bar, ...) behave weirdly, because they did not get properly notified about the change in editor dimensions.

The "vanilla" ACE editor has a `resize()` method to fix just that problem (see [this fiddle](https://jsfiddle.net/1x9pgn2u/1/)).

My request is: please either forward `resize()` in `react-ace`, or call `resize()` internally on `componentWillReceiveProps` in case that `width` and/or `height` has changed.

**EDIT:** I had a quick look at the source code. You actually do this:

    if(nextProps.height !== this.props.height){
      this.editor.resize();
    }

... but what about changes in width? Shouldn't it be this:

    if(nextProps.height !== this.props.height || nextProps.width !== this.props.width){
      this.editor.resize();
    }

**Comment by securingsincity** [comment]
@MartinHaeusler thanks for the issue. I'm working on this right now. should be out in `4.4.0` and will be in `5.0.0` when that comes out

**Comment by securingsincity** [comment]
@MartinHaeusler this is out now in `4.4.0` Thanks

**Comment by MartinHaeusler** [comment]
Thanks for this very fast response! I just upgraded my package.json to use `4.4.0` and it works very well, thank you!

**Comment by dmigo** [comment]
@MartinHaeusler could you probably share a link to solution you created?

**Comment by MartinHaeusler** [comment]
@dmigo: I tried using [react-measure](https://github.com/souporserious/react-measure) for the job. However, it only worked in some cases, not all of them. There were always some odd corner cases left where the editor wouldn't behave as intended. In the end, I switched from Ace to CodeMirror for that reason. I had some issues there as well with making things resizable and had to do some quite ugly hacks, but that works now. Sorry, I discarded the prototype for the resizable react-ace editor shortly after. But it never really worked properly as intended anyways.

**Comment by dmigo** [comment]
@securingsincity the solution looks nice and clean.  
Do you have any ideas on how to trigger resize when you don't change the `hight` as a component's property, but just use `'100%'` instead?

**Comment by dmigo** [comment]
@securingsincity 
Trying to implement something similar to what @MartinHaeusler did, I found out an interesting behaviour of `react-ace`. It seemed that `resize()` wasn't happening properly.  
After some investigation it turned out that `this.editor.resize()` is being called on `componentWillReceiveProps` which occurs before `render`. It would make more sense to call `this.editor.resize()` during `componentDidUpdate`, after `render` happened and `ace-editor` received new values for `height` and `width`.  
If we agree on that, then I would be happy to fix this one for you (along with #212). What would you say?

**Comment by securingsincity** [comment]
@dmigo that sounds great! If we think that could solve the issues let's do it

**Comment by MartinHaeusler** [comment]
@dmigo Nice catch! That might have been the issue for me as well.

**Comment by dmigo** [comment]
I'm up to it!

**Comment by wmercer** [comment]
I upgraded to 5.1.2 and calling AceEditor with the props:

    mode: 'json',
    theme: 'chrome',
    readOnly: true

Is there anything I need to add to get it to resize to the container?

**Comment by brandontle** [comment]
> Is there anything I need to add to get it to resize to the container?

Anyone figure out how to automatically resize the container based on user-control?

**Comment by xgaia** [comment]
> Anyone figure out how to automatically resize the container based on user-control?

I succeed by using [react-resize-detector](https://www.npmjs.com/package/react-resize-detector)

```javascript
import AceEditor from 'react-ace'
import ReactResizeDetector from 'react-resize-detector'

export default class myComponent extends Component {

  constructor (props) {
    super(props)
    this.state = {
      editorHeight: 400,
      editorWidth: "auto"
    }
    this.onResize = this.onResize.bind(this)
  }


  onResize (w, h) {
    this.setState({
      editorHeight: h,
      editorWidth: w
    })
  }

  render () {
    <div className="resizable">
     <ReactResizeDetector handleWidth handleHeight onResize={this.onResize} />
     <AceEditor
       height={this.state.editorHeight}
       width={this.state.editorWidth}
     />
    </div>
  }
}
```

CSS of  `resizable` class

```css
.resizable {
    overflow: auto;
    resize: both;
    height: 400px;
    width: auto;
}
```

**Comment by milahu** [comment]
here is a pure css solution, using `resize: both`
```jsx
<AceEditor
  onLoad={editorInstance => {
    editorInstance.container.style.resize = "both";
    // mouseup = css resize end
    document.addEventListener("mouseup", e => (
      editorInstance.resize()
    ));
  }}
/>
```
downside: on resize-larger the editor content is hidden

[here](https://jsfiddle.net/6b2tfspe/1/) is a demo fiddle with vanilla js

**Comment by bassiebangura** [comment]
Thanks @milahu your solution worked perfectly for my use case.

**Comment by dimkajasons** [comment]
Thanks, @milahu your solution works fine. Unfortunately, this approach is not working in safari :( Do someone faced with the same problem. Looks like it's safari specific problem with resizing. You can check it out with the above example

**Comment by milahu** [comment]
> this approach is not working in safari

[yepp](https://caniuse.com/css-resize). try a [polyfill](https://github.com/CezaryDanielNowak/css-resize-polyfill)

**Comment by 01brett** [comment]
@dimkajasons Did you get it working in Safari? I've run into the problem where Safari _has_ resize capability but the composition of the AceEditor hides the ability to drag the corner. It works marvelously in Firefox and Chrome (though the drag indicator doesn't show up). I'm also using TypeScript.

**Comment by karanattriCaw** [comment]
add a className to AceEditor component and use this 

 .ace-editor {
    max-height: 300px;
    min-height: 150px;
    resize: both;
  }
