### ISSUE TITLE
Use peerDependencies for React

### ISSUE THREAD

**Issue by gre** [securingsincity/react-ace#21]
this is a workaround I guess, but you should put React into peerDependencies instead of dependencies.

Because React have issues when you use multiple versions of it, I can't make your module working with latest React.

See a lot of references here: https://www.google.com/?#q=react+peerdependencies

You could just do:

`"peerDependencies": { "react": "*" }`

Thanks

**Comment by securingsincity** [comment]
This should be fixed in 2.0.2
