### ISSUE TITLE
5.0.0 on npm

### ISSUE THREAD

**Issue by niki-m** [securingsincity/react-ace#210]
Simple issue with 5.0.0

ERROR in ../~/react-ace/lib/index.js
Module not found: Error: Can't resolve './ace.jsx' in '(path)/react-ace/lib'

It's looking for a jsx, but the files in lib have a .js extension.  

Other than that, everything's perfect.

**Comment by niki-m** [comment]
(Using with WebPack 2 if that makes a difference)

**Comment by securingsincity** [comment]
Ok that should be fixed in `5.0.1` sorry about that.
