### ISSUE TITLE
ace.resize() should be called on componentDidMount()

### ISSUE THREAD

**Issue by MartinHaeusler** [securingsincity/react-ace#212]
Following up on #207, there is one minor issue left.

Your code currently calls `this.editor.resize();` in `componentWillReceiveProps`. That is totally fine. However, React itself **will not call** `componentWillReceiveProps` if:
 - it is the first call to `render()` (in this case, the constructor is invoked instead)
 - the component is not yet mounted

So, in my case, where I have the editor in a resizeable container, everything works as expected as soon as the container is resized at least once by the user. The *initial* version is unfortunately still not correctly displayed, because the ace editor has not received a call to `resize()` in my case yet (it received a size change after construction, but before mounting, so `componentWillReceiveProps` was not called). 

To correct this issue, may I suggest to call `this.editor.resize()` unconditionally in `componentDidMount`? If the editor did not resize at all, then this method will be effectively a no-op, and if it did resize, it fixes the issue at hand. I do not assume ACE editors to be mounted/unmounted at a rapid rate, so the performance-overhead in the no-op case should not be an issue.

Sorry for pestering you about this issue. If you want, I can provide my full "ResizeableAceEditor" react component for you, maybe it will prove useful to other people as well.

**EDIT** I just did some experimenting. I used a "dirty hack" and fetched the internal `this.editor` field from your `ReactAce` class (using a React `ref` in my container). Calling `resize()` on `componentDidMount(...)` was not enough to fix my issue. In fact, I needed to call it unconditionally on every `componentWillReceiveProps` as well to make it work properly. I don't understand the reasons myself yet...

**EDIT** I discovered some more, very weird behaviours. I have come to believe that it's not `react-ace` or my own code doing funny stuff, but the vanilla `ace` itself might be at fault here.

**Comment by securingsincity** [comment]
Ok sounds like we need to research this one a little more @MartinHaeusler I'll mark this as an issue with Ace for now.

**Comment by aurimasniekis** [comment]
I dont think this helped or etc. Depending on page complexity it can be that editor is not rendered then DidMount is called my trick was this (feels so sketchy...):

![image](https://user-images.githubusercontent.com/15481/53135106-da351800-3571-11e9-9d8d-9cb0f0732314.png)
