### ISSUE TITLE
Is there a changelog anywhere?

### ISSUE THREAD

**Issue by danqing** [securingsincity/react-ace#214]
Thanks for the library! I'm wondering if there's a changelog anywhere. Just saw that the version got bumped to v5, but there wasn't a release note (or maybe I didn't find one). Would be helpful if we can have a changelog to learn about all the great new changes. :)

**Comment by orangecoding** [comment]
👍 Publishing a major version without a changelog is not nice.

**Comment by securingsincity** [comment]
I like to keep y'all guessing... but I guess you can have a [changelog](https://github.com/securingsincity/react-ace/blob/master/CHANGELOG.md) moving forward

**Comment by securingsincity** [comment]
Thanks @danqing @orangecoding for the good call.
