### ISSUE TITLE
Supporting onInput event

### ISSUE THREAD

**Issue by AlonBe** [securingsincity/react-ace#219]
Ace editor has an event named "input" which is called after a timeout when changing the text.
The event seems to be undocumented.
So far i found these details:
1. https://stackoverflow.com/questions/24319514/how-to-ignore-setvalue-in-the-oninput-event-ace-js
2. https://stackoverflow.com/questions/19670178/ace-editor-change-event

I'm using this event since i want to check the UndoManager properties after text change, and it seems that onChange occurs before UndoManager is being changed.

My workaround is to call the editor itself (using ref) and register to the event.
It would be nice if one could passed the event as a prop to react-ace component.

**Comment by securingsincity** [comment]
@AlonBe I'd be open to a pull request on this. No timeline of me doing it myself.
