### ISSUE TITLE
add defaultValue support

### ISSUE THREAD

**Issue by gre** [securingsincity/react-ace#22]
Like React Input components,
it would be great to have a `defaultValue` that only set the value at initial state.

**Comment by securingsincity** [comment]
Not sure how easy this would be being we're using the ace library directly. Would be happy to review a PR for this.

**Comment by gre** [comment]
I guess a simple way to do that would be to wrap the component using https://github.com/jquense/uncontrollable

that would allow both:

`<Ace value={controlledValue} onChange={this.setControlledValue} />`

and

`<Ace defaultValue={initial} onChange={this.onValueChange} />`

(see the subtilities of controlled vs uncontrolled)

Up to you if you want to do that on the lib side or let react-ace users wrap the component themselves.

**Comment by njlr** [comment]
@gre I have a branch with `defaultValue` implemented: https://github.com/njlr/react-ace 

I also filtered the `onChange` events better to allow for this pattern: 

    // constructor
    this.state = {value: '// Hello world'};
    
    // render
    <Ace value={this.state.value} onChange={(value) => this.setState({value}) />
