### ISSUE TITLE
Undo on new editor instance erases entire document

### ISSUE THREAD

**Issue by viridia** [securingsincity/react-ace#223]
I'm using the 'defaultValue' property to pre-populate the editor. If I hit "Undo" before doing any edits, it erases the entire document. If I then hit "redo", the entire document is restored and everything is selected.

It appears that the ace editor is treating the initial document load as an insertion operation and adding it to the undo stack.

BTW I've tried working around this by calling editor.getUndoManager().reset(), but this seems to have no effect, and I'm not sure why.

**Comment by securingsincity** [comment]
@viridia Unfortunately, the way the `react-ace` editor is created there is no way to set an initial value. My advice would be to manage whether to show and `undo` button based on the state outside of the `react-ace` component.

**Comment by azcn2503** [comment]
A workaround I am using to achieve this:

```
<AceEditor
  {...props}
  onLoad={editor => {
    const session = editor.getSession();
    const undoManager = session.getUndoManager();
    undoManager.reset();
    session.setUndoManager(undoManager);
  }}
/>
```

This will clear the undo manager history on startup. From what I understand, the undo stack is appended to when populating the editor with a default value, since it's going from no value to some value, it's counted as a change.

It seemed to work for us anyway!

**Comment by securingsincity** [comment]
@viridia  @azcn2503  i believe #345 will fix your issue moving forward. Will be putting it in the latest version assuming it fits your needs
