### ISSUE TITLE
`setOptions` is overridden by defaultProps of AceEditor

### ISSUE THREAD

**Issue by ben181231** [securingsincity/react-ace#226]
# Problem

As [the documentation](https://github.com/securingsincity/react-ace/blob/90255338bdb4312db6a2caf81decfb153b401a1e/docs/Ace.md) tells, `setOptions` will be apply directly to the Ace editor instance. 

However, some of the options (e.g. `enableBasicAutocompletion`, `enableLiveAutocompletion`, `tabSize`, etc.) will be overridden by the default props because of [these few lines of code](https://github.com/securingsincity/react-ace/blob/90255338bdb4312db6a2caf81decfb153b401a1e/src/ace.js#L71-L80).

## Sample code to reproduce your issue

The following snippet tries to set the tab size to 2. However, it will become 4 as it is the default value of `AceEditor`.

```jsx
// from sample page: http://securingsincity.github.io/react-ace/
<AceEditor
  mode="javascript"
  theme="monokai"
  name="blah2"
  onLoad={this.onLoad}
  onChange={this.onChange}
  fontSize={14}
  height="100%"
  showPrintMargin={true}
  showGutter={true}
  highlightActiveLine={true}
  value=''
  setOptions={{
    enableBasicAutocompletion: false,
    enableLiveAutocompletion: false,
    enableSnippets: false,
    showLineNumbers: true,
    tabSize: 2,
  }}
/>
```

**Comment by securingsincity** [comment]
@ben181231 thanks will look to fix this with the next release.
