### ISSUE TITLE
Can't unset markers after being set

### ISSUE THREAD

**Issue by rexxars** [securingsincity/react-ace#229]
# Problem

When you first apply an array of markers and later want to remove all markers, the editor doesn't update as expected.

This seems to be caused by [this condition](https://github.com/securingsincity/react-ace/blob/master/src/ace.js#L157), which checks that you have markers and that the markers array is not empty. 

To me, it seems like the check could easily just be removed, and in `handleMarkers` only add markers if `markers` is an array. Thoughts?

## Sample code to reproduce your issue

https://www.webpackbin.com/bins/-KniLqaH_Aw8QHKeAUPT

## References

Progress on: #

**Comment by securingsincity** [comment]
@rexxars I think that makes sense. I'll look at getting this out in the next release
