### ISSUE TITLE
Tracking semantic errors

### ISSUE THREAD

**Issue by nitin42** [securingsincity/react-ace#239]
# Problem
Is there any way to track the semantic errors ?

For example - 

We have some JSON data like this

```
[
     {
          name: "Nitin"
     }
]
```
but according to JSON data exchange format, keys should have double quotes. Although `react-ace` shows the error, 

![sample](https://i.gyazo.com/8ebf9158be4f38545d54bafa33d369ca.png)

But is there any way to catch them explicitly ?

Thanks!!

## References

Progress on: #

**Comment by securingsincity** [comment]
I'm not sure what you are looking for @nitin42. When you say catch them, what are your expectations?

**Comment by nitin42** [comment]
Thanks! I was able to tweak what I wanted to do with `react-ace`. Btwn thanks for this awesome component 🎉 😄
