### ISSUE TITLE
Manipulating the editor

### ISSUE THREAD

**Issue by Shriken** [securingsincity/react-ace#24]
Hi! First of all, thanks for making this component. It's been a big help in my development process thus far.

I want to programmatically manipulate the editor, specifically to clear the selection and scroll up. How do I go about getting the editor object?
Normally it would be pretty straightforward, but it's not clear to me how to do so through/around the React  framework.

**Comment by timthez** [comment]
@Shriken You can get the editor object by passing in a function to onLoad. For example, I wanted word wrapping so I did this:
```
onload(editor){
		editor.getSession().setUseWrapMode(true);
	}
	render() {
		return (
			<AceEditor mode='markdown' theme='twilight' onLoad={this.onload} width='100%' name='Editor' onChange={this.change} />
		)
	}
```

**Comment by securingsincity** [comment]
I think this is the best way to approach this @timthez . @Shriken  does that fix your issue?

**Comment by Shriken** [comment]
Yep, that works. Thanks @timthez!
