### ISSUE TITLE
custom mode documentation is lacking

### ISSUE THREAD

**Issue by solemnify** [securingsincity/react-ace#243]
This is in reference to https://github.com/securingsincity/react-ace/issues/126

If a JSFiddle or a working example on how to integrate a custom mode is available, that would be helpful.

Tried following the directions that @AlonBe listed with the custom mode provided by @pollen8 and I cannot unfortunately get the syntax highlighter to register correctly... :(

Any help would be appreciated.

[custom_mode](https://github.com/securingsincity/react-ace/files/1198642/test.txt)

Where my editor is being rendered:

`  
componentDidMount () {
    const customMode = new CustomSqlMode();
    this.refs.ace.editor.getSession().setMode(test);
    console.log(customMode);
}
`

**Comment by SidneyNemzer** [comment]
Maybe it's just me, but the file you attached for "custom_mode" is a text file that says `<script>alert("xss")</script>`
