### ISSUE TITLE
Can't get {e} in 'onBlur event'

### ISSUE THREAD

**Issue by adrianzqt** [securingsincity/react-ace#246]
# When I tried to use {e} in onBlur event , it behaves just like as follows: 

## Sample code to reproduce your issue

handleBlur(e) {
  console.log(e);  //  undefined
}

<AceEditor
  ...
  onBlur={this.handleBlur} />

## References

Progress on: #

**Comment by securingsincity** [comment]
I just looked at this and we don't pass the event along. but i can add that in the next release
