### ISSUE TITLE
OpenCollective error

### ISSUE THREAD

**Issue by nenadlukic** [securingsincity/react-ace#276]
# Problem

Unable to install a clean project due to the following

`npm ERR! enoent ENOENT: no such file or directory, chmod 'src/node_modules/react-ace/node_modules/opencollective/dist/bin/opencollective.js'`

Unable to build any new projects due to this.

**Comment by securingsincity** [comment]
@nenadlukic are you running  `5.2.1`? I removed the running of opencollective in that version?

**Comment by nenadlukic** [comment]
Hmm, I've specified 5.2.0 in the package.json and it works fine then. Also package-lock.json has 5.2.0 after local installation (last working state). Specifying 5.2.1 gives the error from the original post. Also, even if the package has 5.2.0 installing remotely from a clean clone produces the same error.

**Comment by meidan-sundaysky** [comment]
We just encounter the same issue both for 5.2.0 and 5.2.1

**Comment by meidan-sundaysky** [comment]
Problem with opencollective 1.0.4
https://github.com/opencollective/opencollective-cli/issues/3

**Comment by securingsincity** [comment]
Looks like an issue with that package. I'm making a release right now to remove it completely. This is not the first time they've had an issue.

**Comment by securingsincity** [comment]
Hi all this should be resolved with `5.2.2` apologize for any inconvenience @nenadlukic @meidan-sundaysky
