### ISSUE TITLE
remove react and react-dom from npm dependencies

### ISSUE THREAD

**Issue by avanthay** [securingsincity/react-ace#279]
Hi

React should generally never be directly listed in the `dependencies` of a package, instead it should be within the `peerDependencies`.

This package had that correct until commit 0ef6c18dd82afebb758b884333f677e9c6d73d73 a couple of days ago.

Please remove `react` and `react-dom` from the `dependencies` of this project.

Thank you

**Comment by M-ZubairAhmed** [comment]
Hi,
currently in peer dependency react and react-dom versions are 15.0.1 while the ones in dependencies the version is 15.6.2. Should i also add that version in peer too?

**Comment by avanthay** [comment]
Hi @M-ZubairAhmed 

Thank your for picking up my issue.

With the SemVer definition `^15.0.1` NPM will automatically take the newest 15.xx version, therefore it doesn't really matter.
