### ISSUE TITLE
Failed to render AceEditor component after upgrading to version 2.0.2

### ISSUE THREAD

**Issue by jmao** [securingsincity/react-ace#28]
After upgrading to version 2.0.2, my application failed to render AceEditor. React throws an exception when rendering AceEditor. I am using react 0.13.3.

Here is my source:
var React = require('react');
var AceEditor  = require('react-ace');
...
render: function () {
  return (
    <div className="summary-line">
          <AceEditor
            mode="json"
            theme="github"
            name="profile_json_editor"
            value={profile_json}
            width="98%"
            onChange={this.handleEditorChange}
          />
        </div>
  )
}

Here is the stacktrace:

TypeError: 'undefined' is not a function (evaluating 'type.toUpperCase()')
	    at autoGenerateWrapperClass (...node_modules/react/lib/ReactDefaultInjection.js:54:0)
	    at getComponentClassForElement (.../node_modules/react/lib/ReactNativeComponent.js:60:0)
	    at validatePropTypes (.../node_modules/react/lib/ReactElementValidator.js:363:0)
	    at .../node_modules/react/lib/ReactElementValidator.js:409:0
	    at .../node_modules/react/lib/ReactCompositeComponent.js:790:0
	    at .../node_modules/react/lib/ReactCompositeComponent.js:817:0
	    at ReactCompositeComponent__renderValidatedComponent (.../node_modules/react/lib/ReactPerf.js:71:0)
	    at .../node_modules/react/lib/ReactCompositeComponent.js:238:0
	    at ReactCompositeComponent_mountComponent (.../node_modules/react/lib/ReactPerf.js:71:0)
	    at .../node_modules/react/lib/ReactServerRendering.js:69:0
	    at .../node_modules/react/lib/Transaction.js:135:0
	    at renderToStaticMarkup (.../node_modules/react/lib/ReactServerRendering.js:70:0)

**Comment by zallek** [comment]
Same for me.

**Comment by boboTjones** [comment]
Same here. I tried changing the versions of brace, but this just resulted in a different error. Spent half a day trying to figure out what's going wrong, but I ran out of time so I've changed mine to a plain textarea for the time being. Curious to see resolution/workaround.

**Comment by zallek** [comment]
I've create a new repo offering a React component for Ace which **doesn't depends on `brace`** anymore but `ace` itself. https://github.com/zallek/react-ace-async
This is really at early stage, interfaces may change but as you can see in examples I've been able to develop and use my own mode for syntax highlighting

**Comment by securingsincity** [comment]
@zallek this looks promising. brace is a huge dependency. I personally would love to see a completely react built code highlighter.

**Comment by boboTjones** [comment]
@zallek Yep. If you change the main file back to index.js, there is no more error. Thanks!

**Comment by securingsincity** [comment]
Yeah let's switch it back to index.js. this is fixed in `2.0.3`
