### ISSUE TITLE
Not able to extract contents of textarea using e.target.value onblur event.

### ISSUE THREAD

**Issue by shubh28** [securingsincity/react-ace#283]
# Problem
Hi when I am trying to get the contents of code editor onBlur event it is giving me some wierd symbol. I am not sure about the reason for this. Please find my code for the same issue. 

## Sample code

    import React, { Component } from 'react';
    import CodeEditor from 'react-ace';
    class Test extends Component{

        onBlur(e) {
            console.log(e.target.value);
        }
        render(){
            return (
                <CodeEditor mode='python'
                            width='100%'
                            height='600px'
                            value={`Hey there`}
                            onBlur={this.onBlur}
                />
            )
        }
     }

**Comment by securingsincity** [comment]
Hi @shubh28 unfortunately the event won't include the value. You would need to either access the value using a ref or we could add a second argument where the value is passed as the second argument

**Comment by securingsincity** [comment]
@shubh28 i would be open to a PR to add it. If you are not interested in doing it, I'll mark it as something that could be worked on.

**Comment by shubh28** [comment]
@securingsincity I'll check and contribute if possible :)

**Comment by VijayKrish93** [comment]
I created a [PR](https://github.com/securingsincity/react-ace/pull/315) @securingsincity .Please review and merge it. By the way I love this component and been using it in my project

**Comment by securingsincity** [comment]
Thanks @VijayKrish93  this is in `5.7.0`. CC @shubh28
