### ISSUE TITLE
Changing key bindings

### ISSUE THREAD

**Issue by FurcyPin** [securingsincity/react-ace#285]
Hi,

In ace, it is possible to remap a keybinding by using the bindkey method.
For instance, it is possible to write something like this.
```
var editor = ace.edit(id)
editor.commands.bindKey("Ctrl-X", "removeline")
```
Looking at [ace's source code](https://github.com/ajaxorg/ace/blob/5ab93e894dc8c99ed9f7481da5c1787f2a326814/lib/ace/keyboard/hash_handler.js#L90), the second argument of bindKey(key, command, position) can either be a method or a string, in which case the command with that name will be remapped to the new key.

It would be nice to reproduce this feature in react-ace.

I believe it could be done easily be changing [this piece of code](https://github.com/securingsincity/react-ace/blob/c9273b073d261cdd1e3c70804ec9eedb8c9289ce/src/ace.js#L89)
```
if (Array.isArray(commands)) {
  commands.forEach((command) => {
    this.editor.commands.addCommand(command);
  });
}
```

into something like this:
```
if (Array.isArray(commands)) {
  commands.forEach((command) => {
    if(typeof command.exec == "string") {
      this.editor.commands.bindKey(command.bindKey, command.exec);
    }
    else {
      this.editor.commands.addCommand(command);
    }
  });
}
```
Thus, if command.exec is a string, it should simply remap the existing command with the new bindKey.

Please tell me if you think this makes sense, and I can try making a pull request for this 
(I am quite new to web-programming, I am more into Big-Data stuff usually).

**Comment by securingsincity** [comment]
@FurcyPin i think that makes sense maybe you can add a pull request and write some tests to prove it out?

**Comment by FurcyPin** [comment]
Yeah, sure. I will try to do that tomorrow.

**Comment by FurcyPin** [comment]
I just made a pull request: #287
