### ISSUE TITLE
How to set `editor.$blockScrolling = Infinity`?

### ISSUE THREAD

**Issue by oluckyman** [securingsincity/react-ace#29]
I’m getting these warnings:
> Automatically scrolling cursor into view after selection change this will be disabled in the next version set editor.$blockScrolling = Infinity to disable this message

Where should I set `editor.$blockScrolling = Infinity` to prevent these warnings?

**Comment by breakingco** [comment]
please merge this fix by Evan, just came here to ask the same thing :) thanks!

**Comment by mingfang** [comment]
I'm still getting these warnings in the console.
Sounds like it was fixed though.
Is there something I have to set to avoid the warnings?

**Comment by mskasal** [comment]
@mingfang Default value is `0`. I tried to set as `editor.$blockScrolling = 1` and console logs gone.

**Comment by mingfang** [comment]
@mskasal thanks

**Comment by loretoparisi** [comment]
@mskasal I did but this does not solve the issue:

```javascript
this.editor = this._createEditor("editor");
            this.editor.$blockScrolling = 1;
            this.editor.setOptions({
                readOnly: true,
                highlightActiveLine: false,
                highlightGutterLine: false,
                onLoad: function (_editor) {
                    // This is to remove following warning message on console:
                    // Automatically scrolling cursor into view after selection change this will be disabled in the next version
                    // set editor.$blockScrolling = Infinity to disable this message
                    _editor.$blockScrolling = 1
                }
            });
```

where

```javascript
private _createEditor(element_name:string,onchange?:any){
            var editor:Editor = ace.edit(element_name);
            //editor.setTheme('ace/theme/monokai');
            editor.getSession().setMode('ace/mode/javascript');
            editor.getSession().setTabSize(4);
            editor.getSession().setUseSoftTabs(false);
            editor.getSession().setUseWrapMode(true);
            editor.setShowPrintMargin(true);
            return editor;
        }
```

**Comment by harshapps** [comment]
@oluckyman @loretoparisi try this. This worked for me

var editor = ace.edit("editor");        
editor.getSession().setMode("ace/mode/javascript");
editor.setShowPrintMargin(false);

**Comment by harshapps** [comment]
@oluckyman @loretoparisi Try this. This worked for me.

var editor = ace.edit("editor");        
editor.getSession().setMode("ace/mode/javascript");
**editor.$blockScrolling = Infinity;**

**Comment by KevinMongiello** [comment]
How does this work in jsx? `<ReactAce $blockScrolling={<value>} />` doesn't work where value = Infinity, 1, "Infinity", etc.

**Comment by oluckyman** [comment]
@KevinMongiello try this:
```
<AceEditor
  editorProps={{
    $blockScrolling: Infinity
  }}
/>
```

**Comment by KevinMongiello** [comment]
ahh thanks :) @oluckyman
