### ISSUE TITLE
enableLiveAutocompletion seems to have no effect?

### ISSUE THREAD

**Issue by OlafSzmidt** [securingsincity/react-ace#296]
# Problem

Toggling enableLiveAutocompletion to true seems to have no effect on the ace editor in Python mode.

## Sample code to reproduce your issue
```
        <div className="code-editor">
          <AceEditor
            mode="python"
            theme="idle_fingers"
            fontSize={this.state.fontSize}
            name="editor"
            showPrintMargin={false}
            height="100%"
            width="100%"
            value={this.state.textValue}
            onChange={this.onChange}
            enableLiveAutocompletion={this.codeHintsOn}
          />
```

## References

Progress on: #

**Comment by securingsincity** [comment]
@OlafSzmidt I believe you have to enableBasicAutocompletion to allow for live autocompletion as well. I was able to have autocomplete using the example in http://securingsincity.github.io/react-ace/

**Comment by yaderick** [comment]
https://github.com/securingsincity/react-ace/commit/f21a6f8e6593530882625ff5a430f12ee58ed204#comments
