### ISSUE TITLE
Strict Comparison is ComponentDidMount

### ISSUE THREAD

**Issue by VijayKrish93** [securingsincity/react-ace#317]
# Problem
My project is composed of cells which are instances of ReactAce. ReactAce ComponentDidMount has this line of code
```js 
this.editor.setValue(defaultValue === undefined ? value : defaultValue, cursorStart);
```
Here the `defaultValue` is strictly compared with `undefined`.My Parent component has the props `defaultValue` `' '` and `value` as 'some source of code'. This strict comparison ends up mounting an empty editor rather than the editor with the actual source.The work around I am using is to avoid defaultProps in my parent component(This is highly not recommended since its a reusable library component).I think it would be nice to have a negation check instead of strict comparison.

**Comment by VijayKrish93** [comment]
If this is considered to be a potential issue I can contribute myself to fix this

**Comment by securingsincity** [comment]
This is now in 5.8.0
