### ISSUE TITLE
Documentation regarding SplitEditor is misleading

### ISSUE THREAD

**Issue by BoneCrasher** [securingsincity/react-ace#322]
# Problem
Trying to get the SplitEditor working, I referred to the documentation on:
https://github.com/securingsincity/react-ace/blob/master/docs/Split.md

 The example will not work.

Detail the problem here, including any possible solutions.

I realized that without including "import AceEditor from 'react-ace'", I receive the error "AceEditor" not found. 
Including it split's won't work and an exception is thrown trying to dset a value array of strings for the editors.

Searching around a lot, and finally in the "example" subdir of the project I found the correct way to do it, which is "import {split as SplitEditor} from 'react-ace'" and using the <SplitEditor>-tag instead.

**Solution:**
Update the official example to the code below and include references to the code in the example folder while referring to the different live-demos!

```
import React from 'react';
import { render } from 'react-dom';
import brace from 'brace';
import { split as SplitEditor} from 'react-ace';

import 'brace/mode/java';
import 'brace/theme/github';

// Render editor
render(
  <SplitEditor
    mode="java"
    theme="github"
    splits={2}
    orientation="below"
    value={['hi', 'hello']}
    name="UNIQUE_ID_OF_DIV"
    editorProps={{$blockScrolling: true}}
  />,
  document.getElementById('example')
);
`````

## Sample code to reproduce your issue

```

// Original example code
import React from 'react';
import { render } from 'react-dom';
import brace from 'brace';
import { split } from 'react-ace';

import 'brace/mode/java';
import 'brace/theme/github';

// Render editor
render(
  <AceEditor
    mode="java"
    theme="github"
    splits={2}
    orientation="below"
    value={['hi', 'hello']}
    name="UNIQUE_ID_OF_DIV"
    editorProps={{$blockScrolling: true}}
  />,
  document.getElementById('example')
);
```

## References
https://github.com/securingsincity/react-ace/blob/master/docs/Split.md

Progress on: #

**Comment by securingsincity** [comment]
@BoneCrasher do you mind updating the documentation in a pull request?

**Comment by securingsincity** [comment]
Updated the docs
