### ISSUE TITLE
Keydown and Keyup event missing

### ISSUE THREAD

**Issue by VijayKrish93** [securingsincity/react-ace#326]
# Problem

Why the editor does'nt support keydown and keyup events?I want a combination of shift and enter key press to be handled in my project
## References

Progress on: #

**Comment by securingsincity** [comment]
https://github.com/securingsincity/react-ace/blob/master/docs/FAQ.md#how-do-i-add-key-bindings @VijayKrish93 you can add keyboard shortcuts through the commands

**Comment by VijayKrish93** [comment]
@securingsincity Thanks!

**Comment by lightninglu10** [comment]
@securingsincity is there anyway to prevent the default browser behavior?

For example, I'm trying to use command + s as save, but since we don't get any args back we can't prevent the default browser save.

**Comment by lightninglu10** [comment]
Nevermind -- it looks like the default behavior is to prevent default
