### ISSUE TITLE
Undo before any changes clears ace editor

### ISSUE THREAD

**Issue by edmundoa** [securingsincity/react-ace#339]
# Problem
When rendering an `AceEditor` component with a `value` (or `defaultValue`) set, executing an undo command before performing any changes in the editor clears the editor. This behaviour is unexpected and may also lead to a potential lose of data, if a user wasn't careful enough.

Looking at the code, it looks like doing [`setValue`](https://github.com/securingsincity/react-ace/blob/master/src/ace.js#L57) alters the undo history for the editor as it should. This however should not happen on the text editor initialisation.

## Sample code to reproduce your issue
To reproduce the issue, you can render a component, i.e. `<AceEditor value="foobar" />`, and press Ctrl+Z (or Cmd+Z in macOS).

I couldn't find a good way of reproducing the issue during testing, as it seems that Ace is not fully initialised in the `onLoad` callback. I could reproduce the issue using `onInput`, though:
```
    it('should keep initial value after undo event', () => {
      const onInput = () => {
        const editor = wrapper.instance().editor;
        editor.undo();
        expect(editor.getValue()).to.equal('foobar');
      };

      const wrapper = mount(<AceEditor value="foobar" onInput={onInput}/>, mountOptions);
    });
```

A workaround would be to reset the `UndoManager` once after the Ace editor is fully loaded, i.e. `editor.getSession().getUndoManager().reset();`

I am willing to do a PR fixing the issue, but I would probably need a bit more information on how (or when) I could get a fully initialised editor object. Looking at the Ace documentation I could not find any clear event to do this.

## References
Original issue that made me investigate this: https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/224
The full component where I tested the workaround for the issue: https://github.com/Graylog2/graylog2-server/blob/0bd43ce9a9d6e727e6fcf42e97b09f68e11928bd/graylog2-web-interface/src/components/common/SourceCodeEditor.jsx

Progress on: #

**Comment by securingsincity** [comment]
@edmundoa i believe #345 will fix your issue moving forward. Your idea would have also worked however like you said it is hard to see when it is fully loaded. Do you mind verifying it on your end?

**Comment by edmundoa** [comment]
@securingsincity Thank you! I'll take a look and let you know how it goes 👍

**Comment by edmundoa** [comment]
@securingsincity I just tried and it seems to work fine, thank you! :)

**Comment by FerusAndBeyond** [comment]
This issue still exist in 8.0.0
