### ISSUE TITLE
ACE set the initial value, there is no wrap effect, can not format

### ISSUE THREAD

**Issue by Bobcui001** [securingsincity/react-ace#343]
# Problem
ACE set the initial value, there is no wrap effect, can not format
Version: "react-ace": "^5.8.0"
## Sample code to reproduce your issue
```
this.state.SimBody = {"id":123456,"name":"ACE","age":111};
<AceEditor
                    readOnly={fale}
                    onChange={this.handleGetBody}
                    width="100%"
                    height="500px"
                    mode="json"
                    theme="github"
                    name="aceCodeEditor"
                    onLoad={this.onLoad}
                    fontSize={14}
                    showPrintMargin={true}
                    showGutter={true}
                    highlightActiveLine={true}
                    value={this.state.modelBody}
                    editorProps={{
                      $blockScrolling: true,
                      enableBasicAutocompletion: true,
                      enableLiveAutocompletion: true,
                      enableSnippets: true
                    }}
                    setOptions={{
                      showLineNumbers: true,
                      tabSize: 2
                    }}/>
```
## References
React-ace
Progress on: #
It will show like this
![image](https://user-images.githubusercontent.com/18111032/34332103-e8f9df26-e967-11e7-926b-3a02c3664a71.png)
I expect like this
![image](https://user-images.githubusercontent.com/18111032/34332151-49d2df78-e968-11e7-8e7b-d72bcb28ee44.png)

**Comment by securingsincity** [comment]
@Bobcui001 the editor doesn't auto format json as you describe. However to get it into that format `JSON.stringify(this.state.modelBody, null, '\t');` This should pretty print the json as you describe.

**Comment by Aaron-Lei** [comment]
hi, JSON.stringify(this.state.modelBody, null, '\t') did not work, 
when I input 
![image](https://user-images.githubusercontent.com/33127288/54746538-58371e00-4c07-11e9-9e4c-53f24055b69e.png)
and setValue( JSON.stringify(this.state.modelBody, null, '\t')), it returned:

![image](https://user-images.githubusercontent.com/33127288/54746577-80268180-4c07-11e9-98dc-5ac349c9230b.png)

**Comment by jorgepvenegas** [comment]
@Aaron-Lei try
`JSON.stringify(JSON.parse(this.state.modelBody), null, 2);`

where the third param is the number of spaces you want.

**Comment by BrunoQuaresma** [comment]
Same issue of @Aaron-Lei

**Comment by oqx** [comment]
I'm running into this issue as well. I'll see if I can look into it when I have some extra time.
