### ISSUE TITLE
In the Google browser to use the react - ace throw an error Refused to execute script from 'http://city.alibaba.net/p/EF9D4E8884ED6D87CF645121DEA0C35D/device/productaccess/theme-github.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by wanglijson** [securingsincity/react-ace#346]
# Problem

Detail the problem here, including any possible solutions.

## References

Progress on: #

**Comment by securingsincity** [comment]
@wanglijson I don't think I can help without clear reproduction steps. The error seems inline with a configuration issue on the server side. Moving forward please fill out the issue template
