### ISSUE TITLE
this.refs.nickname.editor.insert('some stuff') does not work

### ISSUE THREAD

**Issue by fetacore** [securingsincity/react-ace#348]
Insert is not working when I do this.refs.mainEditor.editor.insert('some value') while it used to work!!! Code does not produce any errors. Here is my component.

`<AceEditor
        mode="tex"
        theme={aceEditorTheme}
        snippets="tex"
        name="mainEditor"
        ref="mainEditor"
        enableBasicAutocompletion
        enableLiveAutocompletion
        wrapEnabled
        editorProps={{
            $blockScrolling: Infinity,
         }}
         width={(editorWidth).toString()+'px'}
         height={(editorHeight).toString()+'px'}
         fontSize={15}
         value={this.state.value}
         debounceChangePeriod={1}
         setOptions={{
             enableSnippets: true,
             behavioursEnabled: true,
             cursorStyle: 'smooth',
             useWorker: false,
             showPrintMargin: false,
          }}
          onChange={this.updateEditorInput.bind(this)}
          onFocus={this.onFocusMainEditor.bind(this)}
/>`

**Comment by fetacore** [comment]
Ok the problem occurs because I use the "debounceChangePeriod" prop. Please help!!

**Comment by securingsincity** [comment]
Without the whole source code it is hard to know what the issue is but can I ask why you are using `insert` and not changing the value prop? if any other properties change or anything else occurs you will face a rerender that will wipe out that insert. Also is the `debounceChangePeriod` necessary? My guess is something is rerendering the ace component and your changes are rerendering. You should try setting a breakpoint in the render function and where your insert happens and seeing if that will explain why its not doing the insert.

**Comment by fetacore** [comment]
There is no rerendering from other points of the code (if I remove the debounce prop then everything works as expected). I use insert in some specific cases where I need to add stuff programmatically at the cursor (user graphically chooses stuff and stuff magically enter the text at the specific location) without slicing and replacing strings. I could do the javascript way and handle input as string but since the api is there I thought of using it. Also I found that the editor could handle change in large texts somewhat faster if I used the prop, especially in undo/redo operations.

**Comment by securingsincity** [comment]
@fetacore  are you doing the insert in the `onChange`? I tried to reproduce this but I don't see how this would work before, as doing the insert fires another `onChange` and eventually you run out of memory. Can you provide the rest of the code of the component?

**Comment by franverona** [comment]
I've just faced a similar situation, @fetacore, where I need to debounce the update and the state wasn't properly being populated.

I solved it by updating the value that it's being passed to the editor, and debouncing the "saving process" only. Like this:

```
import _ from 'lodash';

constructor(props) {
    super(props);
    this.state = {
      // ...
    };
    this.onSave = _.debounce(this.onSave, 2000);
  }

// Data will be saved (to db using API call) by its parent in a debounced way
onSave() {
    const { textContent, liveEditor } = this.state;
    this.props.onChangeMetadata({ text: textContent });
  }

render() {
    const { settings } = this.props;
    const { 
      mode,
      theme,
    } = settings;

    const { textContent } = this.state;
    const { editor } = dimensions;
    return (
      <div ref={ (div) => this._divElement = div } style={{ width: '100%', height: '100%' }}>
        <AceEditor
          name="code-editor"
          value={ textContent }
          mode={ mode }
          theme={ theme }
          onChange={ (value) => {
            this.updateState({ textContent: value });
            this.onSave();  // debounced...
          }}
          editorProps={{ $blockScrolling: true }}
          width={ editor.width }
          height={ editor.height }
          style={{ left: editor.left }}
        />
  );
}
```

I haven't tried `debounceChangePeriod` as I'm using [lodash](https://lodash.com/) for debouncing. Maybe this will give you some light on what can be the issue.

- Fran
