### ISSUE TITLE
Getting the following errors....

### ISSUE THREAD

**Issue by tbowdollar** [securingsincity/react-ace#357]
SyntaxError: expected expression, got '<'
mode-html.js:1
SyntaxError: expected expression, got '<'
theme-twilight.js:1
Error: couldn't load module ace/theme/twilight or it didn't call define

**Comment by securingsincity** [comment]
@tbowdollar Can you provide some more detail? For example, the code being used, and/or the build process (are you using webpack, browserify, rollup etc?).

**Comment by tbowdollar** [comment]
`Code ===>

import AceEditor from 'react-ace'

<AceEditor mode="html" theme="twilight" onChange={this.editorChange} value={this.state.module.html} name="html" editorProps={{$blockScrolling: true}} height="100%" width="100%" />`

**Comment by securingsincity** [comment]
@tbowdollar you need to import those themes and modes separately as show in the basic usage in the readme https://github.com/securingsincity/react-ace#basic-usage .
