### ISSUE TITLE
Undo/Redo doesn't work for Split Editor

### ISSUE THREAD

**Issue by quen2404** [securingsincity/react-ace#365]
# Problem

When instancing a simple Split Editor, like this [exemple](https://github.com/securingsincity/react-ace/blob/master/docs/Split.md), I can't use Ctrl+Z or Ctrl+Shift+Z. It works correctly with Ace Editor.
It doesn't work in your [demo page](http://securingsincity.github.io/react-ace/split.html) too.

## Sample code to reproduce your issue
```
<SplitEditor
  mode="java"
  theme="github"
  splits={2}
  orientation="below"
  value={['hi', 'hello']}
  name="UNIQUE_ID_OF_DIV"
  editorProps={{$blockScrolling: true}}
/>
```

**Comment by securingsincity** [comment]
After working through the source of Brace and Ace they don't start up the default keyboard commands for the split editor. I'll try to get to this soon.

**Comment by securingsincity** [comment]
I'd be welcome to a PR as well.

**Comment by VijayKrish93** [comment]
@securingsincity This issue can be closed

**Comment by securingsincity** [comment]
That's right we can close this as of `5.10.0`

**Comment by securingsincity** [comment]
thanks @Vijayk93
