### ISSUE TITLE
The NPM package should export pure ES5, not JSX

### ISSUE THREAD

**Issue by andrerpena** [securingsincity/react-ace#37]
First, thank you for react-ace, this is awsome but I still can't use it. React-ace 2.0.2 still exports JSX. I mean, the NPM entry point is a JSX file.

Most of the developers using Webpack configures `.jsx` like this:

    {test: /\.jsx/, loaders: ['react-hot', 'babel'], exclude: /node_modules/ },

The `node_modules` is being excluded because that would take too long to `babel` everything from the `node_modules` folder. So, NPM packages targeting Webpack developers can be developed using ES2015 and JSX but they normally **build** the source code and publish it as ES5, so it's regular JavaScript when you import it in Webpack.

So, for now, I'll continue to use https://github.com/eccenca/react-ace-wrapper/ which is a wrapper that does what I need.

A fix would be welcome.

Thank you for your effort again, I really like it.

**Comment by chentsulin** [comment]
#33 may help and resolve this

**Comment by Bjorgvin** [comment]
I just tried using npm package react-ace and had the same problems as @andrerpena so I'm using react-ace-wrapper for now since it works nicely...  thank you

**Comment by securingsincity** [comment]
This should be fixed thanks to @chentsulin for building in support for babel.
