### ISSUE TITLE
Content is reset to value prop value if defaultValue prop changes

### ISSUE THREAD

**Issue by arjunu** [securingsincity/react-ace#373]
# When the default prop changes, the editor sets its content to value prop's value.

This is assuming value prop is undefined because I want the editor to be uncontrolled.

**Expected:** The editor keeps its content in comparison with the behaviour of input element tag which keeps its content even if default prop value changes.

## Code
```javascript
 this.state = {
   editorDefaultValue: 'console.log(a);',
 };

//...

<AceEditor
  mode="javascript"
  theme="tomorrow_night"
  name="UNIQUE_ID_OF_DIV"
  onChange={value => {
    this.setState({
      editorDefaultValue: value
    });
  }}
  defaultValue={this.state.editorDefaultValue}
/>

<input
  defaultValue={this.state.editorDefaultValue}
  onChange={value => {
    this.setState({
      editorDefaultValue: value
     });
  }
/>
```
![ezgif-4-7f4f082d16](https://user-images.githubusercontent.com/4038217/36036291-ce335930-0db9-11e8-8a98-5fd599069b3a.gif)

Full code is here in this sample repo: https://github.com/arjunu/react-ace-default-value

It's the code in componentWillReceiveProps https://github.com/securingsincity/react-ace/blob/dcb43131bc34d30e1049e858fbb90f252228c661/src/ace.js#L195
Here it does not take account of whether the component is uncontrolled or controlled.

**Comment by securingsincity** [comment]
This should be addressed in 9.1.0
