### ISSUE TITLE
setPadding prop

### ISSUE THREAD

**Issue by jcruz** [securingsincity/react-ace#386]
# Problem

Looking to be able to set padding through props. Currently have to do `editor.renderer.setPadding(value)` to set editor padding.

## Sample code to reproduce your issue

For example, trying to set padding through style props doesn't work
```
import React from 'react';
import { render } from 'react-dom';
import brace from 'brace';
import AceEditor from 'react-ace';

import 'brace/mode/java';
import 'brace/theme/github';

function onChange(newValue) {
  console.log('change',newValue);
}

// Render editor
render(
  <AceEditor
    mode="java"
    theme="github"
    onChange={onChange}
    name="UNIQUE_ID_OF_DIV"
    editorProps={{$blockScrolling: true}}
    style={{padding: 8}}
  />,
  document.getElementById('example')
);
```

**Comment by jcruz** [comment]
Ended up setting this property using the `onLoad` prop.

**Comment by tageecc** [comment]
any updates?

**Comment by brandontle** [comment]
> Ended up setting this property using the `onLoad` prop.

Hey @jcruz , do you mind sharing what function you fed into the onLoad prop?

**Comment by jcruz** [comment]
@brandontle yeah, it looks like this:
```javascript
onLoadFunction = editor => {
  editor.renderer.setPadding(8)
}
```

**Comment by brandontle** [comment]
@jcruz Thanks for the reply. It doesn't seem to work for me, although I may be doing something wrong. Was there anything else you did with the editor's style? 

I put up a codesandbox with your recommendation:
https://codesandbox.io/s/vjj92wpz07

**Comment by brandontle** [comment]
@jcruz Sorry, disregard; I got it sorted on the Codesandbox now, but unfortunately, my app doesn't behave the same way. So it must be a styling conflict somewhere in my code. 

Thanks for the help!

**Comment by brandontle** [comment]
But for posterity's sake, the Codesandbox only provided side padding, not top or bottom padding. 

I've been targeting the .ace_content classname in CSS, but if anyone else has a better way for top/bottom padding, would love to hear it.

**Comment by bessarabov** [comment]
> I've been targeting the .ace_content classname in CSS

I've tried to use 

```css
.ace_content {
    padding: 1rem 0.5rem;
}
```

This added padding, but it also broke mouse selection. With this css the mouse selection is mispositioned. At last I've removed this css and used

```jsx
<AceEditor
        ...
        onLoad={function(editor){ editor.renderer.setPadding(10); editor.renderer.setScrollMargin(10); }}
        ...
```
This is not perfect, when you scroll the code in the editor the top "padding" disappears, but for my case it is ok.

**Comment by jkiss** [comment]
> > I've been targeting the .ace_content classname in CSS
> 
> I've tried to use
> 
> ```css
> .ace_content {
>     padding: 1rem 0.5rem;
> }
> ```
> 
> This added padding, but it also broke mouse selection. With this css the mouse selection is mispositioned. At last I've removed this css and used
> 
> ```js
> <AceEditor
>         ...
>         onLoad={function(editor){ editor.renderer.setPadding(10); editor.renderer.setScrollMargin(10); }}
>         ...
> ```
> 
> This is not perfect, when you scroll the code in the editor the top "padding" disappears, but for my case it is ok.

`setScrollMargin(top, bottom, left, right)`
