### ISSUE TITLE
I'm getting a `read property 'ace' of undefined error`

### ISSUE THREAD

**Issue by timothyjlaurent** [securingsincity/react-ace#4]
This builds fine with Babel-loader in webpack when we hit the browser I'm geting cannot read property 'ace' of undefined.

**Comment by securingsincity** [comment]
I'll take a look. I'm not currently using webpack so I'll need to take a look.

**Comment by securingsincity** [comment]
Ok looked into it and it should be fixed with 1.1.2. I didn't have the pragma set on the jsx file. 
Which should be fixed now. Please confirm.

**Comment by securingsincity** [comment]
https://github.com/securingsincity/react-ace-webpack-example a working example using webpack
