### ISSUE TITLE
Debounce Prop not working

### ISSUE THREAD

**Issue by karpkarp** [securingsincity/react-ace#405]
```
<SplitEditor
    debounceChangePeriod={5000}
    mode="python"
    height="700px"
    width="1400px"
    theme="xcode"
    wrapEnabled={true}
    enableBasicAutocompletion={true}
    enableLiveAutocompletion={true}
    splits={2}
    value={editorValues}
    onChange={props.onChange}
    name="UNIQUE_ID_OF_DIV"
    editorProps={{$blockScrolling: true}}
  />
```

A split editor with the following props calls the onChange function with no delay.

**Comment by securingsincity** [comment]
@Vijayk93 i'd really appreciate a PR on this. sorry about the lag time.

**Comment by VijayKrish93** [comment]
@securingsincity No issues about the delay.Please use @VijayKrish93 while referencing me in the issue threads as I had my work github(@Vijayk93) user configured by mistake in the repo config
