### ISSUE TITLE
editor.resize() method?

### ISSUE THREAD

**Issue by ChubbRck** [securingsincity/react-ace#446]
Is there a resize() method for triggering a resize of the editor component? I seem to recall other implementations of Ace editor containing this method.

**Comment by securingsincity** [comment]
https://github.com/securingsincity/react-ace/blob/master/docs/FAQ.md#how-do-call-methods-on-the-editor-how-do-i-call-undo-or-redo

**Comment by ardok** [comment]
@securingsincity I don't get that example.
What is `parent`?

```
import ReactAce from 'react-ace';
class Parent extends Component {
  render() {
    console.log(this.refs.reactAceComponent); // is this it?
    return (
      <ReactAce />
    )
  }
}
```

**Comment by securingsincity** [comment]
@ardok just looking at it i realize it should be `this.refs.reactAceComponent` 

where you define a ref on the ReactAce component 
```

onChange() {
  this.refs.reactAceComponent.editor.resize()
}

render() {
  return <div>
    <AceEditor
      onChange={this.onChange}
      ref="reactAceComponent"
    />
  </div>;
}

```
