### ISSUE TITLE
GutterRenderer

### ISSUE THREAD

**Issue by dlochynski** [securingsincity/react-ace#488]
Hey everyone.

Thanks for a great editor. I had a problem when using the editor, I tried to overwrite the gutterRenderer according to: https://stackoverflow.com/questions/28311086/modify-the-gutter-of-ajax-org-cloud9-editor-ace-editor?rq=1

Have anyone found a solution for that?

**Comment by VijayKrish93** [comment]
@dlochynski  Can u share your code here. Also  a fiddle or Pen(if you have one)
