### ISSUE TITLE
Move away from brace.

### ISSUE THREAD

**Issue by dennisoelkers** [securingsincity/react-ace#512]
# Problem

react-ace is currently using [brace](https://github.com/thlorenz/brace) as the underlying, browserified version of ace. Unfortunately brace is lagging a magnitude of versions behind and any change (feature, bug fix) to ace needs to propagate through brace before it ends up in react-ace. brace's development is currently stalling, with the last commit being done in February, issues not being answered and even PRs (like https://github.com/thlorenz/brace/pull/139) not being accepted and merged. Therefore I would suggest looking for an alternative which allows to benefit from ace development.

## References

Progress on: #

**Comment by securingsincity** [comment]
@dennisoelkers this would be a pretty big change. I'd be up for some help with this just as i don't know if i have the time to do this all myself

**Comment by dennisoelkers** [comment]
@securingsincity I have a working branch ready and I am currently working on the remaining tests that fail. The change does not seem to be too big, so I am happy to help. What were your reasons for using brace instead of ace/ace-builds?

**Comment by securingsincity** [comment]
The interface was cleaner and early on it was easier to work with browserify

**Comment by securingsincity** [comment]
@dennisoelkers I ended up having to roll back that change. It looks like it breaks importing languages and themes. You can see on the examples that themes and languages no longer work after the switch to `ace-builds`

**Comment by dennisoelkers** [comment]
With "example", do you mean `yarn run example` or the [example listed in the README for "basic usage"](https://github.com/securingsincity/react-ace#basic-usage)? The latter requires some changes for sure.

**Comment by manubb** [comment]
The problem with the demos is probably a problem with github pages build.
(Locally, everything is allright.)
See: https://github.com/securingsincity/react-ace/pull/538#issuecomment-425028481
@securingsincity Could you try to merge again and see if the problem comes back?

**Comment by securingsincity** [comment]
This was addressed in v8
