### ISSUE TITLE
How to use the beautify extension?

### ISSUE THREAD

**Issue by JiahuanWu** [securingsincity/react-ace#516]
# how to use the beautify extension

Detail the problem here, including any possible solutions.

I imported the extension in my components, but it didn't work.
`import 'brace/ext/beautify';`

And I see this in the code, but the editor didn't have the beautify command
```
exports.commands = [{
        name: "beautify",
        exec: function(editor) {
            exports.beautify(editor.session);
        },
        bindKey: "Ctrl-Shift-B"
    }]
```

**Comment by rndm2** [comment]
Same problem for me. Did you solve it?

**Comment by KirillYoYo** [comment]
+1

**Comment by jdhamp** [comment]
The following is how I got it to work
``` javascript
import Beautify from 'brace/ext/beautify'; //'ace-builds/src-noconflict/ext-beautify';

const editor = document.getElementById('EditorId').env.editor;
Beautify.beautify(editor.session);
```

**Comment by lidianhao123** [comment]
It's work:
```ts
import Beautify from 'ace-builds/src-noconflict/ext-beautify';

        <AceEditor
            ref={editorRef}
            value={value}
            commands={Beautify.commands}
        />
```

**Comment by JiahuanWu** [comment]
This issue was created a long time ago, and it looks like it's working now. So I'm closing it.

**Comment by JiahuanWu** [comment]
This issue was created a long time ago, and it looks like it's working now. So I'm closing it.
