### ISSUE TITLE
Demos Appear Broken 

### ISSUE THREAD

**Issue by JordanSjodinFaithlife** [securingsincity/react-ace#537]
# Problem

When attempting to view the demo [here](http://securingsincity.github.io/react-ace/) I don't seem to see anything being syntax highlighted and there are many errors in the console.

I tried from multiple browsers with the same result.

![screen shot 2018-09-26 at 3 22 36 pm](https://user-images.githubusercontent.com/17711909/46112693-57658800-c1a0-11e8-8495-cb6a0c118691.png)

**Comment by securingsincity** [comment]
Looks like the update removing brace as a dependency caused this issue.

**Comment by securingsincity** [comment]
After rolling back that change these are fixed again. Thanks.
