### ISSUE TITLE
May need a editorOptions

### ISSUE THREAD

**Issue by crysislinux** [securingsincity/react-ace#54]
just like editorProps, add a new editorOptions to support editor options.

Options such as maxLines, readOnly, tabSize can be implement in this way.

### Advantages:
* automatically support all options that ace editor support.
* cut down on  code

### Disadvantages:
* cannot limit data type cleanly.

I do not think the data type (now limited by propTypes) is a big problem.

If you think it is a good idea. I will implement it (reserve the old supported options by props now).

**Comment by izolate** [comment]
Here I thought editorProps **was** editorOptions. Ability to configure ACE is a must.

**Comment by securingsincity** [comment]
#83  should resolve this issue.
