### ISSUE TITLE
misspelled options - again!

### ISSUE THREAD

**Issue by kolbinski** [securingsincity/react-ace#548]
# Problem

Problem reported here https://github.com/securingsincity/react-ace/issues/95 was believed to be fixed, but unfortunately still occurs:
Getting some warnings in console:
misspelled option "enableBasicAutocompletion"
misspelled option "enableLiveAutocompletion"

# Detail the problem here, including any possible solutions.

Remedy for this problem was supposedly this PR https://github.com/securingsincity/react-ace/pull/127, but it solved only some cases - for others, problem still happens.

Based on error details, similar changes as in that PR https://github.com/securingsincity/react-ace/pull/127/files  should also be applied here: https://github.com/securingsincity/react-ace/blob/87bd672673d344d7e3eb3d5ec0ec0308c2223a3e/src/ace.jsx#L181

## Sample code to reproduce your issue

Just use editor with some options, ie:
```
<AceEditor
  setoptions={{
    enableBasicAutocompletion: true,
    enableLiveAutocompletion: true,
    enableSnippets: true
  }}
/>
```
and make sure, that componentDidUpdate was triggered.

## References

Progress on: #

**Comment by kolbinski** [comment]
Closing - this issue can be solved by adding `import 'brace/ext/language_tools';`

**Comment by ziishaned** [comment]
I solved it by following:

```ts
import "ace-builds/src-noconflict/ext-language_tools";
```

**Comment by gone-skiing** [comment]
@ziishaned this import does not seem to fix it for me. What are your imports and what order?

**Comment by KhizerRehan** [comment]
@ziishaned Thanks it worked. I upgrade "react-ace": "6.3.2" to "react-ace": "^9.2.1".

Thus `react-ace` does no longer use `brace` package from v8 onwards.

https://github.com/securingsincity/react-ace/issues/638#issuecomment-649181737

Therefore had to import extension tools package from "ace-builds/src-noconflict/ext-language_tools";


Migration Guide from v6 -> 8
https://github.com/securingsincity/react-ace/blob/main/docs/Migrate-v7-to-v8.md

**Comment by KhizerRehan** [comment]
@gone-skiing 
import 'ace-builds/webpack-resolver';
import 'ace-builds/src-noconflict/mode-java';
import 'ace-builds/src-noconflict/ext-language_tools';

...
Worked for mine.
