### ISSUE TITLE
Custom modes

### ISSUE THREAD

**Issue by YourPsychiatrist** [securingsincity/react-ace#557]
I created a custom mode using the [Ace mode creator](https://ace.c9.io/tool/mode_creator.html) but I can't seem to figure out how to use it. I looked at the "example" in the FAQ but that did not help at all since I do not know much about the structure of ace or react-ace. I am just submitting an issue because I am really desparate and need some help to get this working. Could anyone give me a direction?

**Comment by adesurirey** [comment]
This has worked for me : https://github.com/securingsincity/react-ace/issues/126#issuecomment-345151567

**Comment by securingsincity** [comment]
I have added the example from that issue to the docs
