### ISSUE TITLE
Pressing key immediately after double clicking to select causes wrong cursor and selection position

### ISSUE THREAD

**Issue by ghost** [securingsincity/react-ace#586]
# Problem

I'm getting odd behavior from the editor whenever I try to immediately insert something into selected text. The problem doesn't seem to be originated from my code.

## How to reproduce:

Go to http://securingsincity.github.io/react-ace/
Double click on any text to select it
Immediately press any key
The selected text will be replace by the key, but the editor will automatically move the cursor to the right and select the text.

**Comment by securingsincity** [comment]
Not able to reproduce
