### ISSUE TITLE
Any plan to support react v0.14.0 ?

### ISSUE THREAD

**Issue by hidekoji** [securingsincity/react-ace#59]
I want to use react-ace with react v0.14.0 but it looks like latest react-ace (2.5.0) does not support react v0.14.0 yet..

```` {shell}
npm ERR! peerinvalid The package react@0.14.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-ace@2.5.0 wants react@>=0.11.2 <1.0.0 || ^0.14.0-rc
````

**Comment by securingsincity** [comment]
Would be happy to take a PR for this.

**Comment by chentsulin** [comment]
@securingsincity  Is also a time to drop react 0.11, 0.12 support now?

**Comment by soulmachine** [comment]
Looking forward to  React v0.14 support :+1:

**Comment by diorahman** [comment]
+1

**Comment by chentsulin** [comment]
I can prepare a PR after #62 being merged
