### ISSUE TITLE
How to access the content of the editor ?

### ISSUE THREAD

**Issue by boopathi** [securingsincity/react-ace#6]
When I use

```js
handleChange(newValue) {
  this.setState({content: newValue});
}
```

it fails. Two change events are fired, one with the character typed, and the consecutive one with an empty string. But, interestingly, if I do this, it works.

```js
handleChange(newValue) {
  console.log(newValue);
}
```

So, how do I get the value stored in the Ace editor ?

**Comment by okjake** [comment]
If you add a ref when you render the component, eg:

    <AceEditor
        ref="ace"
        ...
    />

Then you can later access the entire content using:

    this.refs.ace.editor.getValue();

**Comment by boopathi** [comment]
Ah! Cool. Din't strike my mind even though I saw `this.editor` being used in the code.
Thanks!
