### ISSUE TITLE
placeholder prop doesn't work

### ISSUE THREAD

**Issue by harry0071** [securingsincity/react-ace#613]
# Problem
I have set the placeholder prop，but it didn’t work

## Sample code to reproduce your issue
demo👉 [click me](https://codesandbox.io/s/kkpx4q1r55?fontsize=14)

## References

Progress on: #

**Comment by suifengfengye** [comment]
@harry0071 这个问题解决了么？

**Comment by ghostlpx** [comment]
Excuse me, this problem has been solved yet

**Comment by securingsincity** [comment]
This is live on version `6.5.0`
