### ISSUE TITLE
How to disable shortcut annotations and set useWorker invalid

### ISSUE THREAD

**Issue by zhangshuai0101** [securingsincity/react-ace#616]
![image](https://user-images.githubusercontent.com/40013310/55125792-c0c15600-5145-11e9-80cc-21b276082247.png)
@SidneyNemzer @securingsincity Seek your help

**Comment by SidneyNemzer** [comment]
I just tested this with the latest versions of react-ace and brace, with _JavaScript_ mode. `useWorker: false` does disable linting.

Ace does not include a worker for python, so I'm not sure what you expect this to do...

**Comment by zhangshuai0101** [comment]
> I just tested this with the latest versions of react-ace and brace, with _JavaScript_ mode. `useWorker: false` does disable linting.
> 
> Ace does not include a worker for python, so I'm not sure what you expect this to do...

I use command +/ shortcut to annotate the edited code. Now I want to disable this operation. How do I do it? Setting userWoker? But the grammar is not Python yet in effect
@SidneyNemzer  thanks

**Comment by SidneyNemzer** [comment]
Cmd + / is the shortcut to toggle a comment, right? You want to disable that shortcut? Workers just do linting, they don't handle shortcuts.

**Comment by zhangshuai0101** [comment]
> Cmd + / is the shortcut to toggle a comment, right? You want to disable that shortcut? Workers just do linting, they don't handle shortcuts.

Yes,I want to disable that shortcut, Is there any way? thanks @SidneyNemzer

**Comment by SidneyNemzer** [comment]
You'll need to do that through Ace. I mean, react-ace _could_ provide an API for that but I think it's kind of a unique use-case.

Call this function:

    editor.commands.removeCommand('togglecomment')

And maybe again for `toggleBlockComment`, if you'd like to disable that too.

See the commands [defined here](https://github.com/ajaxorg/ace/blob/ed0a1219c206fdda8d420538a3b7b922d56d299d/lib/ace/commands/default_commands.js#L473-L485).

**Comment by zhangshuai0101** [comment]
> toggleBlockComment

It solved my problem , Thank you very much

**Comment by zhangshuai0101** [comment]
> You'll need to do that through Ace. I mean, react-ace _could_ provide an API for that but I think it's kind of a unique use-case.
> 
> Call this function:
> 
> ```
> editor.commands.removeCommand('togglecomment')
> ```
> And maybe again for `toggleBlockComment`, if you'd like to disable that too.
> 
> See the commands [defined here](https://github.com/ajaxorg/ace/blob/ed0a1219c206fdda8d420538a3b7b922d56d299d/lib/ace/commands/default_commands.js#L473-L485).

It solved my problem , Thank you very much @SidneyNemzer

**Comment by shivangp76** [comment]
Just in case anyone was wondering how to accomplish this:
```
const onLoad = (editor) => {
  editor.commands.removeCommand(editor.commands.byName.indent);
  editor.commands.removeCommand(editor.commands.byName.outdent);
}
return (
  <Ace
    {...props}
    onLoad={onLoad}
  />
)
```
