### ISSUE TITLE
When switching between two tabs, AceEditor does not keep original line positions

### ISSUE THREAD

**Issue by xutaoustc** [securingsincity/react-ace#623]
# Problem
There are two tabs, under each there is a AceEditor component. 
1.  Tab1 scroll to line number 100, tab2 scroll to line number 200
2. Switch to tab2, and scroll to line 300. 
3. Switch back to tab1, the content there is scrolled to some other line else. It does not keep the original line number it was posited.
![image](https://user-images.githubusercontent.com/22539180/55699146-03174c80-59fc-11e9-8aeb-78fb7ca1de13.png)

Detail the problem here, including any possible solutions.

## References

Progress on: #

**Comment by jahidzaynal** [comment]
This is possibly due to your handling of the tab selection. With every tab selection, React might be re-rendering the component, which as far as ReactAce is concerned is a fresh creation. So it goes to the end of file again (i.e. default line selection or ReactAce at the moment).

**Comment by securingsincity** [comment]
i believe @jahidzaynal nailed it here. Closing.
