### ISSUE TITLE
NOT AN ISSUE: How do new versions get built

### ISSUE THREAD

**Issue by jahidzaynal** [securingsincity/react-ace#624]
This isn't a problem but a question. Apologies, didn't find anywhere else to ask.

I can see `master` branch has a few commits that haven't yet made it into a version tag. Given some commits have been there for some time, what is your process of getting changes into versions on npm registry?

**Comment by securingsincity** [comment]
Hi @jahidzaynal I want to apologize. I had a child recently so I have been slacking on creating new releases. I'm hoping to have the newest release up tomorrow with some changes that have been on master for a while. Normally it's just updating the package.json and creating a new tag

**Comment by jahidzaynal** [comment]
@securingsincity no need to apologise! Congratulations on your new baby :)

**Comment by securingsincity** [comment]
Finally got around to a release!
