### ISSUE TITLE
maxLines use in Diff expects function (?), but documentation says to send number

### ISSUE THREAD

**Issue by bluepeter** [securingsincity/react-ace#625]
Console error:

> Failed prop type: Invalid prop `maxLines` of type `number` supplied to `DiffComponent`, expected `function`.

[Documentation](https://github.com/securingsincity/react-ace/blob/master/docs/Diff.md#available-props):

> maxLines |   | Number | Maximum number of lines to be displayed

**Comment by securingsincity** [comment]
This has been resolved in past releases.
