### ISSUE TITLE
brace should be exported to avoid duplication in webpack bundle

### ISSUE THREAD

**Issue by ohadlevy** [securingsincity/react-ace#638]
This is a follow up to https://github.com/securingsincity/react-ace/issues/142, when using react-ace, I end up having two versions of brace in my bundle, the first one is via a dependency of brace in our package.json, the second is its required to interact with ace to change themes, syntax highlighting etc.

I suggest to export brace so a consumer (an application using react-ace) can import brace from 'react-ace', this will avoid the duplication in bundle size, and ensure the same version of brace is used across.

**Comment by securingsincity** [comment]
We no longer use brace. this can be closed.
