### ISSUE TITLE
Disable auto loading theme

### ISSUE THREAD

**Issue by ialexi-bl** [securingsincity/react-ace#647]
# Problem

I'm using react-ace in my application and I'm loading themes directly from `brace` with dynamic import, because I cannot rely on react-ace auto loading in my code. But every time the page reloads, `react-ace` component is trying to load theme from `/theme-[theme name]` route, which doesn't exist and which I don't want to create. I would like to have a feature that would let me disable this auto loading and either just pass the theme name or set the className myself. Is it possible?

**Comment by ialexi-bl** [comment]
I found out, that this problem is actually caused by the "brace" module

**Comment by catsaremine** [comment]
And can you tell me how you fixed it?

**Comment by ialexi-bl** [comment]
@catsaremine, unfortunately, I wasn't able to fix it, because this problem is caused by the 'brace' module, which always tries to load modes and themes.
So the only think I was able to do is to import things I need manually and add this error to filters in Dev tools so that I couldn't see it anymore :)

**Comment by catsaremine** [comment]
Well, I found that if you always set the `mode` and `theme` props to the editor the errors are gone. 
`plain_text` for `mode` and `chrome` for `theme` are my defaults.
