### ISSUE TITLE
Invoke focus on editor?

### ISSUE THREAD

**Issue by mcarlone** [securingsincity/react-ace#65]
Is there a ref within the component that we can get our hands on, such that we can fire dom events? Specifically, is there a way to put focus on the editor (other than clicking it by hand). Thanks.

**Comment by Xazzzi** [comment]
@mcarlone, check this:
```
<ReactAce onLoad={(editor) => {
  this.codeEditor = editor;
  this.codeEditor.focus();
}} editorProps={{$blockScrolling: Infinity}}/>
```
One issue with this is that `onLoad` triggers not only on actual mount but somehow on each `value` or oter property change (at least for me).

**Comment by elijahsmith** [comment]
@mcarlone I found that by setting a ref on the Ace editor:
```
<AceEditor ref="code"...>
```
I can then dereference the editor instance "inside" the component:
```
this.refs.code.editor.focus();
```

**Comment by securingsincity** [comment]
thanks for the tip @elijahsmith
