### ISSUE TITLE
Cannot use the scrollbars to move around the document

### ISSUE THREAD

**Issue by HenryTux** [securingsincity/react-ace#663]
# Problem
I am rendering AceEditor in a tool I am currently developing with `react 16.8.6`, `react-native 0.57.8`, `react-native-web`, `react-dom 16.8.6` and `react-ace 7.0.2`

I am able to get the editor to show up, I can interact with it no problem. The syntax for a json I am using it for works just fine. I can change the content and get the updated value. But, **I cannot use the scrollbars to actually move around the document itself**. Arrow keys in the keyboard will do the job but I would like the user to be able to use the scrollbars or else I will have to hide them.

I have also tried different props (not quite sure what _blockScrolling_ does, I see no difference in the editor behavior). I get the onScroll event only when I scroll with the arrow keys.

Any ideas on what may be causing this issue? I am using Chrome 75

Thanks in advance!

## Sample code to reproduce your issue
import AceEditor from 'react-ace'
import 'brace'
import 'brace/mode/json'
import 'brace/theme/github'
...
I return this in the render():
```
<AceEditor
        value={stringifiedJSON}
        onChange={value => this.setState({ stringifiedJSON: value })}
        mode="json"
        theme="github"
        editorProps={{ $blockScrolling: true }}
/>
```

**Comment by securingsincity** [comment]
I'm unable to reproduce this issue.
