### ISSUE TITLE
How do I add a custom error in the gutter?

### ISSUE THREAD

**Issue by ryaneid** [securingsincity/react-ace#676]
I'm using react-ace to write a custom JS Editor. I want to throw a custom error in the gutter when the user tries to import a module other than ones from a list I specify. How do I go about doing this? I've tried extending a custom mode but this seems to only customize syntax highlighting, I've peaked around ESLint but am not sure if that's the right path. Please help I'm quite lost.

**Comment by mnmistake** [comment]
@tannerlyons did you manage to do it?

**Comment by mnmistake** [comment]
@ryaneid  did you managed to do it?
