### ISSUE TITLE
Console error coming from ace.js in updatePlaceholder  function

### ISSUE THREAD

**Issue by BrianJVarley** [securingsincity/react-ace#702]
hi @securingsincity 
# Problem

I update the AceEditor value prop via props passed from parent. On every update of the props value a console.error is triggered from `ace.js` the `updatePlaceholder` function. The error is coming from `session`  var evaluating to null.

This console error doesn't effect the render of the editor, it still works as expected and updates the value. But as we are using this in production we can't have this console error bubbling up on the console in user's browser.

_possible fix_

Debugging the code below I see that `editor` exists, but at some point it tries to access `session`.. `!editor.session.getValue()` which is null. So maybe a simple check here can suppress the error in console:

```
ReactAce.prototype.updatePlaceholder = function () {
    // Adapted from https://stackoverflow.com/questions/26695708/how-can-i-add-placeholder- 
   text-when-the-editor-is-empty
    var editor = this.editor;
    var placeholder = this.props.placeholder;
    var showPlaceholder = editor.session ? !editor.session.getValue().length : false;
    .....
  };

```

```
core.js:4799 ERROR TypeError: Cannot read property 'session' of null
    at t.updatePlaceholder (ace.js:417)
    at t.onInput (ace.js:334)
```

## Sample code to reproduce your issue

```
import brace from 'brace';
import _ from 'lodash';
import React from 'react';
import AceEditor from 'react-ace';
import styled from 'styled-components';
import { IYamlViewerProps } from './IYamlViewer.d';

import 'brace/mode/sass';
import 'brace/theme/solarized_dark';

export class YamlViewer extends React.Component<IYamlViewerProps, {}> {


  public createYamlViewer = (yamlString: string) => {
      return (
        <AceEditor
          placeholder={`Yaml value not supplied.`}
          mode="sass"
          theme="solarized_dark"
          showPrintMargin={false}
          showGutter={true}
          fontSize={14}
          width={'auto'}
          height="inherit"
          highlightActiveLine={true}
          value={yamlString? yamlString: ''}
          setOptions={{
            showLineNumbers: false,
            tabSize: 2,
          }}
          editorProps={{ $blockScrolling: true }}
        />
      );
  };

  public render() {
    const StyledEditor = styled.div`
      * {
        font-family: consolas;
        line-height: 1;
      }
    `;

    return (
      <>
        <StyledEditor>
          {this.createYamlViewer(this.props.yamlString))}
        </StyledEditor>
      </>
    );
  }
}
```

export default YamlViewer;

## References

<img width="293" alt="ace-session-err" src="https://user-images.githubusercontent.com/6731968/63902409-d1575e80-ca4c-11e9-8fca-4845c9dc73ae.PNG">

Not referenced elsewhere in issues.

**Comment by amymc** [comment]
+1 also having this issue

**Comment by bamtheboozle** [comment]
still having this issue. any updates?

**Comment by Luleherll** [comment]
Having the same issue

**Comment by KatyaBorodina** [comment]
issue still exists, any updates?

**Comment by nightwing** [comment]
@KatyaBorodina are you using the latest version of ace 1.4.11? If yes could you give the stack trace for the error you are seeing because the original issue was fixed some time ago.

**Comment by KatyaBorodina** [comment]
@nightwing I'm using react-ace (7.0.2)

**Comment by nightwing** [comment]
which version of ace-builds do you use with it?

**Comment by securingsincity** [comment]
@KatyaBorodina react ace 8 or greater would get you on a newer version of ace-builds which @nightwing points out solved this issue.
