### ISSUE TITLE
Special characters are clearing the whole code when typed.

### ISSUE THREAD

**Issue by itspauloroberto** [securingsincity/react-ace#703]
# Problem

The problem is: when you type a special character, for example, `é` or `ç` everything on the code editor goes blank, and after that, you get the character that you did type.

## Sample code to reproduce your issue

Have a `<AceEditor>` component having a `value` attribute bonded to a state property and an `onChange` event handler that uses the argument as the code content and set the state property to the new value. 

## Observations

When the special character is typed, a blank value goes as the argument of the `onChange` handler for reasons that I don't know. I tried to validate if the argument comes blank do not set the State, but the problem still persists, only changes, and now the special character is printed on the first line and the first column of the code editor and your cursor is moved to that place as well.

**Comment by securingsincity** [comment]
I'm unable to reproduce this issue.
