### ISSUE TITLE
Add padding code

### ISSUE THREAD

**Issue by Angelk90** [securingsincity/react-ace#705]
# Problem
Hi @securingsincity , It would be possible to add a padding in the upper and lower part of the module.
Example to see with images.
![Screenshot_20190901_190350](https://user-images.githubusercontent.com/20476002/64079765-c4a46600-cceb-11e9-8f6a-4bee61d65f46.png)
![Screenshot_20190901_190848](https://user-images.githubusercontent.com/20476002/64079780-10efa600-ccec-11e9-806f-15a80e879254.png)

**Comment by securingsincity** [comment]
This project won't be styling the component. You can probably add that padding in your own css.
