### ISSUE TITLE
Enable autocompletion

### ISSUE THREAD

**Issue by arunkumar413** [securingsincity/react-ace#713]
# Problem
Enabling enableBasicAutocompletion, enableLiveAutocompletion, enableSnippets

I had enabled the live autocompletion in the component but the browser console shows the below error. Could you please guide to enable these features?

` ReactAce: editor option enableBasicAutocompletion was activated but not found. Did you need to import a related tool or did you possibly mispell the option? 
    in ReactAce (created by MyEditor)
    in MyEditor `

## Sample code to reproduce your issue
https://stackblitz.com/edit/react-ceb4gg?file=index.js

**Comment by MMrj9** [comment]
same problem

**Comment by securingsincity** [comment]
You need to include 
```      
setOptions={{
            enableBasicAutocompletion: true,
            enableLiveAutocompletion: true,
          }}
``` 
which adds the autocomplete suite. If you look at the example in the  example folder you can see how that works. At this link http://securingsincity.github.io/react-ace/ you can edit the left hand side and it will show you how to turn on those features.

**Comment by MMrj9** [comment]
I was missing:
```
import "ace-builds/src-min-noconflict/ext-language_tools";
import "ace-builds/src-noconflict/snippets/python";
```
also, enableBasicAutocompletion and are props from the AceEditor
so its actually:
```
enableBasicAutocompletion={true}
enableLiveAutocompletion={true}
enableSnippets={true}
```
