### ISSUE TITLE
Incorrect mine-type for tomorrow theme

### ISSUE THREAD

**Issue by arunkumar413** [securingsincity/react-ace#714]
# Problem
For the tomorrow theme the request is  .js file but the browser is receiving text/html mime type and it's not executing.

Detail the problem here, including any possible solutions.

## Sample code to reproduce your issue
https://stackblitz.com/edit/react-egjxfv?file=index.js

**Comment by sillyslux** [comment]
in line 11 you have
`import 'brace/theme/github';`
add this in the next line and it will work
`import 'brace/theme/tomorrow';`

**Comment by securingsincity** [comment]
@sillyslux is correct in v7 or lower. Closing
