### ISSUE TITLE
TypeError ace.require is not a function when adding a custom mode

### ISSUE THREAD

**Issue by sergibondarenko** [securingsincity/react-ace#722]
# Problem

I follow this example https://github.com/securingsincity/react-ace/blob/master/docs/FAQ.md#how-do-i-add-a-custom-mode

The editor is not loaded and I see the error
```
TypeError: ace.require is not a function
```

## Sample code to reproduce your issue
Codesandbox: https://codesandbox.io/embed/ace-worker-wrqij

The custom mode:
```
import "ace-builds/src-noconflict/mode-json";

const JsonHighlightRules = window.ace.acequire("ace/mode/json_highlight_rules")
  .JsonHighlightRules;
const JsonMode = window.ace.acequire("ace/mode/json").Mode;
const WorkerClient = window.ace.acequire("ace/worker/worker_client")
  .WorkerClient;

export default class CustomMode extends JsonMode {
  constructor() {
    super();
    this.HighlightRules = JsonHighlightRules;
  }

  createWorker = session => {
    const worker = new WorkerClient(
      ["ace"],
      "ace/mode/json_worker",
      "JsonWorker"
    );
    console.log("worker", worker);
    worker.attachToDocument(session.getDocument());

    worker.on("lint", results => {
      session.setAnnotations(results.data);
    });

    worker.on("terminate", () => {
      session.clearAnnotations();
    });

    return worker;
  };
}
```

## References

Progress on: #

**Comment by schmave** [comment]
For what it's worth, I ran into a similar problem and it went away after I deleted my node_modules directory and re-ran `npm install`.

**Comment by beerose** [comment]
I just had the same issue, downgrade `ace-builds` to `1.3.1` helped.

**Comment by VienNguyen24hdev** [comment]
Hi everyone, I got same issue.
I try with this way @beerose but it does not work for me.
Which version did you use for react-ace?

**Comment by beerose** [comment]
Hi @VienNguyen24hdev,
I'm using `"8.0.0"`  for react-ace.

**Comment by beerose** [comment]
In another project, I have react-ace: `8.0.0` and ace-build installed as react-ace's dependency in version  `^1.4.6`

**Comment by VienNguyen24hdev** [comment]
Oh I got the problem.
react-ace did not work on `react-boilerplate`.
I just add react-ace to CRA and it works well now.
@beerose 
Thank you for your response!

**Comment by alexks007** [comment]
![image](https://user-images.githubusercontent.com/77754143/134723363-3a835b9b-8bdd-4b1f-85ec-375c7fafe7cf.png)
I`ve got same issue.

**Comment by alexks007** [comment]
![image](https://user-images.githubusercontent.com/77754143/134723514-b3b63e06-8831-403c-bd91-15cfb6586c8e.png)
This is my source code.
Pls help me.
