### ISSUE TITLE
Unnecessary line in the center of editor

### ISSUE THREAD

**Issue by ahmedsalihh** [securingsincity/react-ace#727]
I'm using react ace on my project.
I didn't use split view or something but i see some vertical line center of my screen.
I couldn't find any solution.
here is the screen.

![image](https://user-images.githubusercontent.com/13359680/67079393-c80c8780-f19b-11e9-8cdf-49224157f7bc.png)

I suspect it happens because of browser zoom level but it doesn't change.

**Comment by securingsincity** [comment]
@ahmedsalihh this is the print margin. There is a prop showPrintMargin that you can set to false and this will hide it. You can see that in the demo http://securingsincity.github.io/react-ace/ if you tab a lot in the editor.
