### ISSUE TITLE
Cannot edit without weird re-printing characters

### ISSUE THREAD

**Issue by alexec** [securingsincity/react-ace#734]
# Problem

Whenever you type, you get duplicate characters:

![Screen Shot 2019-10-29 at 11 34 10](https://user-images.githubusercontent.com/1142830/67798063-16454480-fa40-11e9-95f2-46e6ff8cc30f.png)

## Sample code to reproduce your issue

* Clone https://github.com/alexec/cnv
* Run `yarn start`
* Type characters in, see how they are .duplicated and the cursor jumps around.

This is the actual code:

```
                <AceEditor
                  mode={this.state.stack[i].type}
                  theme={"github"}
                  tabSize={2}
                  name={`editor-${i}`}
                  value={this.state.stack[i].value}
                  readOnly={i > 0}
                  width={"auto"}
                  editorProps={{ $blockScrolling: true }}
                  onChange={e => this.change(e.target.value)}
                />
```

**Comment by nightwing** [comment]
Duplicated text usually means that there is an unhandled error in the onchange listener, according to https://github.com/securingsincity/react-ace#basic-usage `e` is the `value` not an event object.

**Comment by alexec** [comment]
Lets try that...

**Comment by alexec** [comment]
Fixed!

**Comment by alexec** [comment]
Thank you.
