### ISSUE TITLE
How to fold code programatically?

### ISSUE THREAD

**Issue by hkedia321** [securingsincity/react-ace#739]
# Problem
I want to programatically fold code i.e have a button to fold all the code at the widgets. Is there any available functionality to do that?

**Comment by nightwing** [comment]
Use `editor.execCommand("foldall")` or `editor.session.foldAll()` where editor is the ace instance that can be obtained using ref https://github.com/securingsincity/react-ace/blob/master/docs/FAQ.md#how-do-i-add-a-custom-mode
