### ISSUE TITLE
prevent unexpected horizontal scroll

### ISSUE THREAD

**Issue by stuartcrobinson** [securingsincity/react-ace#744]
# Problem

when width is 100% clicking on long lines causes the editor to scroll to the right, making usage difficult

![est](http://g.recordit.co/GN8NCeqjcK.gif)

👉**is there any way to disable this action?** 👈

i tried playing around with these settings, nothing helped.

```
wrapBehavioursEnabled
autoScrollEditorIntoView
behavioursEnabled
wrapBehavioursEnabled
autoScrollEditorIntoView
animatedScroll
scrollPastEnd
```

btw i noticed that this scroll issue doesn't happen for this resizable ace editor: http://jsfiddle.net/neilwightman/5enkmmos/3/

## Sample code to reproduce your issue

```
<AceEditor
                      mode="html"
                      theme="monokai"
                      ref={ ref => { this.aceEditor = ref; } }
                      onChange={this.onChangeContent}
                      name="1234"
                      value={content}
                      style={{ height: 'calc(100vh - 108px)', width: '100%' }}
                    />
```

**Comment by nightwing** [comment]
This can happen when the size of the editor.container is changed without calling editor.resize(), e.g. if a parent node is resized.
Editor scrolls, because it expects its size to be smaller.

**Comment by stuartcrobinson** [comment]
thank you! that was helpful.  i fixed this by waiting to resize the editor in the browser after it was rendered
