### ISSUE TITLE
useState value not updating onChange

### ISSUE THREAD

**Issue by Fluidbyte** [securingsincity/react-ace#748]
# Problem

Simply trying to update a functional component using `useState` seems to work and update the editor but I'm unable to access the value outside of this.

## Sample code to reproduce your issue

```javascript
const Editor = ({ runCode }) => {
  const [snip, setSnip] = useState("console.log('hello world')\n")
  const save = () => {
    console.log('RUN', snip)
    runCode(snip)
  }
  const onChange = value => {
    console.log('SET TO', value)
    setSnip(value)
    console.log('NEW STATE', snip)
  }
  return (
    <div className='editor'>
      <AceEditor
        mode='javascript'
        onChange={val => onChange(val)}
        name='editor'
        theme='twilight'
        fontSize={16}
        value={snip}
        setOptions={{ useWorker: false }}
        height='100%'
        width='100%'
        commands={[
          {
            name: 'run',
            bindKey: { win: 'Ctrl-s', mac: 'Command-s' },
            exec: save
          }
        ]}
      />
    </div>
  )
}
```

When I run the above, the `onChange` will show the value correctly for `SET TO` log, however the `NEW STATE` log contains the same value as it started with (i.e. no change).

Additionally the `save` function sees `snip` as the original, starting value of the editor.

**Comment by securingsincity** [comment]
I think you are experiencing : https://reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function which is a similar issue that happens with setState https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous 

Here is an example where i think you want  to read that state value :  https://codesandbox.io/s/ace-worker-3-toqg9

**Comment by securingsincity** [comment]
Closing as there has been no update.

**Comment by enahs** [comment]
@securingsincity Given that the main point of an editor is to modify the state of files, and the main point of react is to keep track of your UI's state, it seems like this issue warrants at least some documentation on the proper way to use the `useState` hook to get at the current value of the editor. 

The react documentation above kind of handwaves at this, but a concrete example would be meaningful.
I was able to circumvent this by adding a local variable, but it gets hosed on re-render and i end up having to manage the state independently of the onChange call which is basically not what you'd expect. 

do I need to pass a closure? how does this work? what's the proper way to get at the editor's current state?

**Comment by doug-shontz** [comment]
I came upon this ticket looking for an answer and thought I would post my solution here for useState (with TypeScript).  I am using react-ace to edit JSON in this example, but I imagine it would work in most cases:

```
    const [editorValue, setEditorValue] = React.useState<string>(JSON.stringify(originalValueHere, null, "\t"));

                            <AceEditor
                                wrapEnabled={true}
                                width="450px"
                                mode="json"
                                theme="dawn"
                                name="myName"
                                onLoad={(editor) => {
                                    editor.getSession().setValue(JSON.stringify(originalValueHere, null, "\t"));
                                }}
                                onChange={(e) => setEditorValue(e)}
                                setOptions={{ useWorker: false }}
                                editorProps={{ $blockScrolling: true }}
                            />
```

I am using the onLoad to set the editor's session value with the initial prop (can be a const or whatever...but cannot be something in useSession.  It must be something "stable" and "unchanging".  Then I set the session state for useSession in the onChange of the AceEditor.  That way Ace has it's "own thing" that it manages while "reporting back to you" what is necessary to use in state.

**Comment by lsbyerley** [comment]
@doug-shontz thanks for the example... i seem to be getting an error in `setValue()` if the `originalValueHere` data is null and still loading from an api response. Have you had this issue?
