### ISSUE TITLE
Cursor is offset after scale transformation

### ISSUE THREAD

**Issue by maayanalbert** [securingsincity/react-ace#750]
# Problem
After scaling, cursor doesn't appear in the place where the mouse clicks.

<img width="247" alt="Screen Shot 2019-12-05 at 2 27 44 AM" src="https://user-images.githubusercontent.com/18056644/70213544-8dd55600-1707-11ea-8861-c8a1a1702661.png">

I found an [identical issue](https://github.com/ajaxorg/ace/issues/3520) in the ace github, but I'm not sure if there's an applicable solution for this component.

## Sample code to reproduce your issue
Alter the scale of the component with something like `style={{transform: "scale(0.5)"}}` in the Ace Editor or some parent div

I'm really stuck on this one, not sure how to resolve it. Any help would be greatly appreciated!

**Comment by nightwing** [comment]
You can set `hasCssTransforms` option to `true` with `setOptions={{ hasCssTransforms: true }}`.

**Comment by maayanalbert** [comment]
That worked! Thanks nightwing, I really appreciate the tip :)
