### ISSUE TITLE
themes and modes doesnt work, looks for them on root

### ISSUE THREAD

**Issue by gochev** [securingsincity/react-ace#766]
# Problem

After installing and using the ace editor exactly as shown on the demo I get an error that the theme and the mode are not found stating: Unable to infer path to ace from script src, use ace.config.set('basePath', 'path') to enable dynamic loading of modes and themes or with webpack use ace/webpack-resolver

The ace editor works without theme and highlight 

## Sample code to reproduce your issue

just create an react app from react start an app and add react-ace editor.

## References

Progress on: #

**Comment by gochev** [comment]
I guess the issue might be related to https://github.com/ajaxorg/ace-builds/issues/129

**Comment by HenningCash** [comment]
Hi, the following worked for me:

1. Install `react-ace` and `ace-build`
2. `import 'ace-builds/webpack-resolver'` or import each theme/mode explicitly
3. Use `<AceEditor />` but do not use the full path for `mode` like `ace/mode/c_cpp` but only `c_cpp`! The same applies to themes.

Example:

```tsx
import AceEditor from 'react-ace'
import 'ace-builds/src-noconflict/mode-c_cpp'
import 'ace-builds/src-noconflict/theme-github'

// alternative (but bundles A LOT OF FILES!)
//import 'ace-builds/webpack-resolver'

<AceEditor
      mode="c_cpp"
      theme="github"
  />
```

Here is the reason why:
https://github.com/securingsincity/react-ace/blob/e8cd14f24d43dd425969efdfd407616e999239e8/src/ace.tsx#L221-L222

**Comment by securingsincity** [comment]
@HenningCash is correct, you need to import the theme/mode explicitly
