### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by dmavrin** [securingsincity/react-ace#79]
When i press ctrl + f to show search box, i get following error:

```
Uncaught TypeError: Cannot read property 'Search' of undefined
```

Have anyone manage to get search box to work?

**Comment by chentsulin** [comment]
It seems throw in this line:
https://github.com/ajaxorg/ace/blob/master/lib/ace/commands/default_commands.js#L183

**Comment by dmavrin** [comment]
Found solution. 

ES6 solution: 
```
import 'brace/ext/searchbox';
```

**Comment by mingfang** [comment]
@dmavrin that works. thanks
