### ISSUE TITLE
Unable to push editor on drawer open  !! Pushing the drawer causes horizontal scroll to not work 

### ISSUE THREAD

**Issue by mohsinxx365** [securingsincity/react-ace#803]
`    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      style={
        open
          ? {
              overflow: "auto",
              height: "calc(100vh - 41px)",
              marginTop: "41px",
              marginLeft: "240px"
            }
          : {
              overflow: "auto",
              height: "calc(100vh - 41px)",
              marginTop: "41px"
            }
      }
    >
      <AceEditor
        style={{
          fontFamily: "Fira Code,Consolas",
          height: "100%"
        }}
        ref={ref}
        fontSize="14px"
        showPrintMargin={false}
        value={value}
        enableBasicAutocompletion={true}
        enableLiveAutocompletion={true}
        mode="javascript"
        theme="chrome"
        setOptions={{
          enableSnippets: true,
          autoScrollEditorIntoView: true
        }}
        onChange={handleChange}
      />
    </motion.div>
  );
}`

**Comment by nightwing** [comment]
This may be caused by autoScrollEditorIntoView, try using `autoScrollEditorIntoView: false`

**Comment by mohsinxx365** [comment]
That is not the issue I have tried it.The issue is something else. 
Anyways thanks for replying.
If u find any other solution please let me know

**Comment by mohsinxx365** [comment]
I got the solution here : 
[https://github.com/securingsincity/react-ace/issues/207](url)

**Comment by mohsinxx365** [comment]
I got the solution here :
https://github.com/securingsincity/react-ace/issues/207
