### ISSUE TITLE
Setting value prop

### ISSUE THREAD

**Issue by garrettmaring** [securingsincity/react-ace#86]
When setting the value pronto include new lines and tabs, I had to use html symbols instead of \n, \r, \t etc. Is this intended behavior?

**Comment by grzeskiba** [comment]
Any solution?

**Comment by securingsincity** [comment]
If you use javascript's template literals multiline string that works well. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Multi-line_strings
