### ISSUE TITLE
Cannot reset Editor Content

### ISSUE THREAD

**Issue by DavidSichau** [securingsincity/react-ace#894]
# Problem

If a empty value is passed to the editor component after it contains some value it is not reset to the empty value

## Sample code to reproduce your issue

The reason is the following line in ace.tsx: https://github.com/securingsincity/react-ace/blob/main/src/ace.tsx#L345

Here it is checked if `nextProps.value` has a value. But if one wants to reset the value this would be also the case. I do not understand why this check was included @gchallen 

## References

https://github.com/securingsincity/react-ace/blob/main/src/ace.tsx#L345

https://github.com/securingsincity/react-ace/pull/857

**Comment by korgon** [comment]
Just encountered this issue and was puzzled...

**Comment by rickbergfalk** [comment]
I'm hitting this as well. It seems this was done to allow the Ace editor to work as an uncontrolled component, but breaks controlled. 

I noticed an update was published a few days ago but this fix wasn't pulled in. Any intention of pulling the fix in @securingsincity?

**Comment by gchallen** [comment]
Sorry... my mistake. The check should be against `undefined`, since I forgot that the empty string is false-y in JS. (Doh.)
