### ISSUE TITLE
Big bundle size.

### ISSUE THREAD

**Issue by boopathi** [securingsincity/react-ace#9]
I use webpack, and after minification using UglifyJs, the bundle size comes to around ~=1.6MB (just react + react-ace). Do you have any suggestions to optimize the bundle size ?

**Comment by boopathi** [comment]
How do you remove the modes and themes while bundling ?, One way I see it is to use webpack's async require on those bundles, and it would just work. I don't know about how it ll be treated in browserify.

**Comment by securingsincity** [comment]
Agreed. The size of this package is comically large. I think you are right in that webpack might be the right way to go. I'll investigate for next version. I don't use webpack currently and I'm not using this module in production anywhere so I would totally be up for investigating for version 2 where webpack would be required for async requiring.

**Comment by securingsincity** [comment]
#17  should fix this issue. And will be released in 2.0

**Comment by securingsincity** [comment]
Check out version 2.0.0 thanks to @schloerke for his awesome work on making this a much smaller piece of functionality.
