### ISSUE TITLE
Disable syntax checker

### ISSUE THREAD

**Issue by ghiden** [securingsincity/react-ace#94]
I'd like to disable syntax checker as my editor is a partial html editor.
I found two ways to achieve this but I need an access to the editor instance or mode prototype
http://stackoverflow.com/a/13016089/729454
https://groups.google.com/forum/?fromgroups=#!topic/ace-discuss/bOovWtXhtdE

Any suggestion for achieving this?

**Comment by ghiden** [comment]
I found a way to get a reference to the editor instance
https://github.com/securingsincity/react-ace/issues/65

**Comment by m-allanson** [comment]
For anyone else that's looking for this, here's a working ES6 code example:

```
<AceEditor
  mode="css"
  theme="github"
  onLoad={(editor) => {
    editor.getSession().setUseWorker(false)
  }}
/>
```

**Comment by SuperAL** [comment]
#168 
this works too
```
setOptions={{useWorker: false}}
```
