### ISSUE TITLE
Is there any way to get value by line number??

### ISSUE THREAD

**Issue by yeukfei02** [securingsincity/react-ace#944]
I know I can `onChange` to get value from react ace editor.
But how to get new value by `line number`?

like 
```
def test():
   print(123)

test()
```

I want to get value in a list:
```
['def test():', '  print(123)', '', 'test()']
```

**Comment by mindhacker0** [comment]
did u solve that problem?

**Comment by yeukfei02** [comment]
> did u solve that problem?

hey think no need for now, will close this issue
