### ISSUE TITLE
misspelled options

### ISSUE THREAD

**Issue by beckend** [securingsincity/react-ace#95]
Getting some warnings in console:

misspelled option "enableBasicAutocompletion"
misspelled option "enableLiveAutocompletion"

**Comment by pgilad** [comment]
This seems to be caused by https://github.com/securingsincity/react-ace/commit/f21a6f8e6593530882625ff5a430f12ee58ed204

**Comment by pgilad** [comment]
After a little more debugging, you can get rid of the warning by importing:
`import 'brace/ext/language_tools';`

Although this is kinda stupid because there is no need to require it in the first place.

**Comment by beckend** [comment]
So the warning is harmless anyways?

**Comment by pgilad** [comment]
Yeah you are trying to `setOption` on an unknown option in terms of `ace` (because the `language_tools` file wasn't loaded).

That said - this is a mistake that happened in one of the commits that I mentioned. I wouldn't include the file if I were you, but revert to version `3.1.0` since that file is around ~2000 lines of code. (That's what I did for now)

**Comment by wldcordeiro** [comment]
This issue and #101 are both regressions that I found problematic as they cause an infinite loop that crashes my application

**Comment by pgilad** [comment]
Is there any plan to fix this issue?

**Comment by inoas** [comment]
We considered moving away from https://github.com/JedWatson/react-codemirror because at least **at the moment** it is not maintained well (aka the maintainer does not merge or reacts to PRs) but this here is a blocker that stops that.

**Comment by securingsincity** [comment]
@inoas this should be fixed by @pgilad 's pr but are you still seeing issues?

**Comment by inoas** [comment]
It is not yet in a release tag, right? @securingsincity

**Comment by securingsincity** [comment]
@inoas this was released over a year ago.

**Comment by Banjerr** [comment]
just caught this issue, using the latest version though. adding `import 'brace/ext/language_tools';` did clear up a few, i'm left with `enableEmmet` and `useElasticTabstops` though
