### ISSUE TITLE
Add react 15 support

### ISSUE THREAD

**Issue by levithomason** [securingsincity/react-ace#99]
React 15 was [released](https://facebook.github.io/react/blog) a couple weeks ago.  Basic use of `react-ace` seems to work OK, however, it is throwing a peerDep error:

```shell
› npm ls react
PROJECT @0.0.1 /My/system/path
`-- UNMET PEER DEPENDENCY react@15.0.1

npm ERR! peer dep missing: react@^0.13.0 || ^0.14.0, required by react-ace@3.2.0
npm ERR! code 1
```

**Comment by securingsincity** [comment]
3.3.0 resolves this issue

**Comment by levithomason** [comment]
Confirmed, thanks a bunch!
